table 'DIM_Danh mục_Hệ số SizeShop'
	excludeFromModelRefresh
	lineageTag: 0e91da25-5d6e-49b9-a241-4fd0e5de61e7

	column Index
		dataType: string
		lineageTag: 00e878d9-64a1-4d5e-8f59-eaf6552fa187
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column Size
		dataType: string
		lineageTag: c2610289-391d-41e3-a881-c51c120bc6b6
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	column 'Hệ số'
		dataType: double
		lineageTag: 45ed032b-bdc7-4048-94f0-f4f7a6570ba0
		summarizeBy: sum
		sourceColumn: Hệ số

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Index.1'
		dataType: int64
		formatString: 0
		lineageTag: df5398d9-4ff5-47af-b756-43cfbfb7d495
		summarizeBy: sum
		sourceColumn: Index.1

		annotation SummarizationSetBy = Automatic

	partition 'DIM_Danh mục_Hệ số SizeShop' = m
		mode: import
		queryGroup: 'Danh mục'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUXIEYkM9U6VYnWglIyDbCcw3AvONgWxnEB/MMwGyXIDYQM8CzDcFsl1h/FgA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Index = _t, Size = _t, #"Hệ số" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Hệ số", type number}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Index.1", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

