table 'DIM_Danh mục_Miền'
	excludeFromModelRefresh
	lineageTag: bab4f185-696d-48ec-9791-d1c3a1b4da73

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 5afdf1ff-9960-4059-872d-41c9a5270f07
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Miền
		dataType: string
		lineageTag: b27bea16-ad1f-4c4c-a106-f820889d222a
		summarizeBy: none
		sourceColumn: Miền

		annotation SummarizationSetBy = Automatic

	partition 'DIM_Danh mục_Miền' = m
		mode: import
		queryGroup: 'Danh mục'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQrJP7wgT6Gw9OHuiclKsTrRSkZAQd/Mh7sb8xScHu5aDxE0Rgj6JeYqxcYCAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Miền = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}, {"Miền", type text}})
				in
				    #"Changed Type"

