table 'DIM_Danh mục_Cách thức xếp hạng'
	excludeFromModelRefresh
	lineageTag: d3699756-33b0-4962-9c8b-2a1d220cee35

	column 'Cách thức xếp hạng'
		dataType: string
		lineageTag: dbade290-e1a9-4b0a-91ac-a2c0acd2531e
		summarizeBy: none
		sourceColumn: Cách thức xếp hạng
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Thứ tự xếp hạng'
		dataType: string
		lineageTag: 47c31de1-252c-4de9-8c84-1e862a5a5b37
		summarizeBy: none
		sourceColumn: Thứ tự xếp hạng

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 6c06f6cc-6ea8-4892-a3b9-aa8032e0fee9
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition 'DIM_Danh mục_Cách thức xếp hạng' = m
		mode: import
		queryGroup: 'Danh mục'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("XU89S8NAGP4rDzfXgHVzExdBG4SqCDFDOSV30FyrXsRVHMTNDM42dqsWFLccxeGC/+P9J74XjKDj+7zPZ5KI5sFXRiHTvsI11Z9TKKork+GS6hWa8uuN3FxCKj2CVX7G3D6M8h/5puiJ9QjHrWg8YZUWaS8Ra4jDG8MBrvwMw8P9E9NhWz/YYDdmdT/CAblHDmtKTe42R7x3tNOabFM974L4S+6m+NfoT9lgalX4PPE1Dahl4GwCS+6FIcnz2OzZ4JTcO0+58AsTUKlg/ZJXdRValSJ3x3mubCmQ5JYjhPUZcv/K7POCCxqM/SriIRu/QyQr72G1XxShNtcQafoN", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Cách thức xếp hạng" = _t, #"Thứ tự xếp hạng" = _t]),
				    #"Added Index" = Table.AddIndexColumn(Source, "Index", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

