table 'F_Tham gia đào tạo'
	lineageTag: ce14c1a7-2c05-4d4a-9694-1b37b5a3854e

	column STT
		dataType: int64
		formatString: 0
		lineageTag: 145541e6-c0eb-446c-ba79-ec3dead78098
		summarizeBy: sum
		sourceColumn: STT

		annotation SummarizationSetBy = Automatic

	column SHOP
		dataType: string
		lineageTag: d3fe018a-92a5-4162-bca0-e0ccdc02ae2b
		summarizeBy: none
		sourceColumn: SHOP

		annotation SummarizationSetBy = Automatic

	column AM
		dataType: string
		lineageTag: 7f159e72-2b9e-4edc-b9b0-dc71e763e15e
		summarizeBy: none
		sourceColumn: AM

		annotation SummarizationSetBy = Automatic

	column MÃ
		dataType: string
		lineageTag: efeb1ed8-b283-46d8-838d-4e0bdbf8e5dc
		summarizeBy: none
		sourceColumn: MÃ

		annotation SummarizationSetBy = Automatic

	column 'VỊ TRÍ'
		dataType: string
		lineageTag: aa16128e-7b4e-4b82-ba30-a8b29683b356
		summarizeBy: none
		sourceColumn: VỊ TRÍ

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8a7b80bc-001a-4a4b-bd98-af5225809951
		summarizeBy: none
		sourceColumn: StartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Tỉ lệ tham gia'
		dataType: double
		lineageTag: 8c41fe83-ecf5-462e-9544-b4cc3fa81191
		summarizeBy: sum
		sourceColumn: Tỉ lệ tham gia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SM/SUP
		dataType: string
		lineageTag: 273eed74-e622-402a-9005-2e6333acd4a8
		summarizeBy: none
		sourceColumn: SM/SUP

		annotation SummarizationSetBy = Automatic

	partition 'F_Tham gia đào tạo' = m
		mode: import
		queryGroup: NLVH
		source =
				let
				    Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject="cellphones-data-platform"]){[Name="cellphones-data-platform"]}[Data], "---""dataset_id=6e97d189-0524-457d-bd6e-30d5e5ad63ad""#(lf)#(lf)SELECT#(lf)  shop AS SHOP,#(lf)  am AS AM,#(lf)ma as `MÃ`,#(lf)    DATE(start_date, ""Asia/Ho_Chi_Minh"") AS StartDate,#(lf)  sm_sup as `SMSUP`,#(lf)stt as STT,#(lf)vi_tri as `VỊ TRÍ`,#(lf)ti_le_tham_gia as `Tỉ lệ tham gia`#(lf)FROM `cellphones-data-platform.cps_larkbase.tham_gia_dao_tao`", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"SMSUP", "SM/SUP"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

