table 'F_Xử lý hàng hóa'
	lineageTag: 25eac0b1-10c2-47c1-813e-68c1836a9ba5

	column 'Tháng kiểm kê'
		dataType: string
		lineageTag: a2c06919-c328-45b1-b2e0-8bc3b71efa05
		summarizeBy: none
		sourceColumn: Tháng kiểm kê

		annotation SummarizationSetBy = Automatic

	column 'Ngày kiểm kê'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 22a3520a-7728-4d22-80fa-69480ff14f1d
		summarizeBy: none
		sourceColumn: Ngày kiểm kê

		variation Variation
			isDefault
			relationship: f485e02d-576e-404b-bd27-d7e3c04fd087
			defaultHierarchy: LocalDateTable_54c34047-c364-41e3-ba9e-370375df6627.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Mã shop'
		dataType: string
		lineageTag: ea6da12b-f2e4-4dec-b142-a4538d04957d
		summarizeBy: none
		sourceColumn: Mã shop

		annotation SummarizationSetBy = Automatic

	column 'Cửa hàng'
		dataType: string
		lineageTag: 48e44e67-2554-4223-a4a1-94785d426b3f
		summarizeBy: none
		sourceColumn: Cửa hàng

		annotation SummarizationSetBy = Automatic

	column 'Quản lý shop'
		dataType: string
		lineageTag: 3c012433-642e-4266-ae4d-5a331860f9bb
		summarizeBy: none
		sourceColumn: Quản lý shop

		annotation SummarizationSetBy = Automatic

	column 'Số tiền'
		dataType: int64
		formatString: 0
		lineageTag: 39d2bd8c-c43e-4b2f-84ee-f3680d848656
		summarizeBy: sum
		sourceColumn: Số tiền

		annotation SummarizationSetBy = Automatic

	column 'Phân loại'
		dataType: string
		lineageTag: 43fbdf4f-414a-4ef6-a85b-fa059089d06f
		summarizeBy: none
		sourceColumn: Phân loại

		annotation SummarizationSetBy = Automatic

	column 'Ghi chú'
		dataType: string
		lineageTag: fdb184d3-2b11-4bdd-b1b7-cedb1b2a0c96
		summarizeBy: none
		sourceColumn: Ghi chú

		annotation SummarizationSetBy = Automatic

	column 'Thay đổi tháng tính thất thoát'
		dataType: string
		lineageTag: 68cb32cc-b8c7-4c5a-bbbe-303745f32b66
		summarizeBy: none
		sourceColumn: Thay đổi tháng tính thất thoát

		annotation SummarizationSetBy = Automatic

	partition 'F_Xử lý hàng hóa' = m
		mode: import
		queryGroup: NLVH
		source =
				let
				  Source = Excel.Workbook(Web.Contents(#"Kiểm kê hàng hóa"), null, true),
				  #"Filtered rows" = Table.SelectRows(Source, each [Item] = "data"),
				    data_Sheet = #"Filtered rows"{[Item="data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(data_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Ngày kiểm kê", type date}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Tháng kiểm kê", "Ngày kiểm kê", "Mã shop", "Cửa hàng", "Quản lý shop", "Số tiền", "Phân loại", "Ghi chú", "Thay đổi tháng tính thất thoát"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Other Columns",{{"Số tiền", Int64.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","CPS-HCM-Q05-785THĐ","CPS-HCM-Q05-785THD",Replacer.ReplaceText,{"Mã shop"}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Value", each ([Ngày kiểm kê] <> null))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

