table 'FACT_Sale_Doanh số bán'
	lineageTag: 276389e2-162b-45e6-bd14-513adb45aad1

	column CreateDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 1f3f0270-e6c4-43a9-ab5f-48d676132573
		summarizeBy: none
		sourceColumn: CreateDate

		variation Variation
			isDefault
			relationship: 16fbe4ee-72e2-4acf-9cd9-e97ce77c7643
			defaultHierarchy: LocalDateTable_9d3733e1-26b2-4e31-9e5f-d0c61935d446.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 384d32e4-03a4-44e2-8fb2-c28b8276407d
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DMC3
		dataType: string
		lineageTag: 5ea2412e-096d-47a3-9a53-50e12c9961f9
		summarizeBy: none
		sourceColumn: DMC3

		annotation SummarizationSetBy = Automatic

	column AutoCode
		dataType: string
		lineageTag: daa372f6-3332-4b58-af2f-862087b785a0
		summarizeBy: none
		sourceColumn: AutoCode

		annotation SummarizationSetBy = Automatic

	column ProductCode
		dataType: string
		lineageTag: 40576f4d-db2c-4dfc-8e23-c410838a3ddd
		summarizeBy: none
		sourceColumn: ProductCode

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 5ea38393-053f-4f1b-a60d-e7f4e42ee9b8
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column MethodName
		dataType: string
		lineageTag: 04485cfa-63b9-4766-b713-fc9e50e25c13
		summarizeBy: none
		sourceColumn: MethodName

		annotation SummarizationSetBy = Automatic

	column centerid
		dataType: int64
		formatString: 0
		lineageTag: e16cef0b-c3ed-449c-a758-a3576bcd3d11
		summarizeBy: sum
		sourceColumn: centerid

		annotation SummarizationSetBy = Automatic

	column StoreCode
		dataType: string
		lineageTag: da99f2dd-aff6-4830-ad36-f433293ff34f
		summarizeBy: none
		sourceColumn: StoreCode

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: double
		lineageTag: f11588fb-ca0a-4d90-b8e0-1012057db99a
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SaleEmployeeCode
		dataType: string
		lineageTag: 9792a069-c918-4eff-b3df-eceb485ca9da
		summarizeBy: none
		sourceColumn: SaleEmployeeCode

		annotation SummarizationSetBy = Automatic

	column Dso
		dataType: double
		lineageTag: f1dcd177-46a0-41fe-8be7-e39cc4b2d56e
		summarizeBy: sum
		sourceColumn: Dso

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SL
		dataType: double
		lineageTag: 28115d7c-6c02-4f5e-8805-179d7a992d5e
		summarizeBy: sum
		sourceColumn: SL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IsSale
		dataType: int64
		formatString: 0
		lineageTag: a6eb3fe8-5be6-4b64-a088-a14edaaf4165
		summarizeBy: sum
		sourceColumn: IsSale

		annotation SummarizationSetBy = Automatic

	column 'Nhóm giá'
		dataType: int64
		formatString: 0
		lineageTag: a6d676d3-4b32-4d7f-b713-41869ea54e0f
		summarizeBy: sum
		sourceColumn: Nhóm giá

		annotation SummarizationSetBy = Automatic

	column exp_S-Star
		dataType: int64
		formatString: 0
		lineageTag: 018113fd-428f-4a69-8a6f-bc81f2161c47
		summarizeBy: sum
		sourceColumn: exp_S-Star

		annotation SummarizationSetBy = Automatic

	column Shop = RELATED('DIM_Danh mục_Phòng ban'[Cửa hàng])
		lineageTag: 1205cac2-5b82-4f4a-9dca-549b11a98b84
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Check online+B2B' =
			
			IF (
			    'FACT_Sale_Doanh số bán'[StoreCode]
			        IN { "HCM.B2B", "HN.B2B", "HCM.ONL", "HN.HL" }
			            || FIND ( "Kho", 'FACT_Sale_Doanh số bán'[Shop], 1, 0 ) > 0
			            || FIND ( "Phòng", 'FACT_Sale_Doanh số bán'[Shop], 1, 0 ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 1bd7f808-9090-4186-b23e-947ea6fcc523
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column SPTT_Model = CALCULATE(VALUES(FACT_SPTT_SKU[Model]), FILTER(FACT_SPTT_SKU, FACT_SPTT_SKU[SKU] = EARLIER('FACT_Sale_Doanh số bán'[ProductCode]) && FACT_SPTT_SKU[Ngày bắt đầu_Model] <= EARLIER('FACT_Sale_Doanh số bán'[Date]) && FACT_SPTT_SKU[Ngày kết thúc_Model] >= EARLIER('FACT_Sale_Doanh số bán'[Date] )))
		lineageTag: 149c3aa3-bfb7-42df-a9dc-f7531822d6ec
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column StartDate = STARTOFMONTH('FACT_Sale_Doanh số bán'[Date])
		formatString: Short Date
		lineageTag: e2c72b78-b68b-4cde-abbc-56fd0dfa69a1
		summarizeBy: none

		variation Variation
			isDefault
			relationship: ea013167-3b1c-4b56-8944-04ea9c1ad000
			defaultHierarchy: LocalDateTable_0af02a84-ebe6-42ec-b595-b308398d5eb1.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PromotionAmount =
			
			CALCULATE(SUM(FACT_Sale_Voucher[Promotion]),
			    FILTER(FACT_Sale_Voucher,
			        FACT_Sale_Voucher[AutoCode] = EARLIER('FACT_Sale_Doanh số bán'[AutoCode]) &&
			        FACT_Sale_Voucher[ProductCode] = EARLIER('FACT_Sale_Doanh số bán'[ProductCode]) &&
			        FACT_Sale_Voucher[isUsingPromotion] = 1))
		lineageTag: 0abe5e82-127e-4ba9-a25a-4604d176a5ae
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiscountAmount =
			
			CALCULATE(SUM(FACT_Sale_Voucher[DiscountAmount]),
			    FILTER(FACT_Sale_Voucher,
			        FACT_Sale_Voucher[AutoCode] = EARLIER('FACT_Sale_Doanh số bán'[AutoCode]) &&
			        FACT_Sale_Voucher[ProductCode] = EARLIER('FACT_Sale_Doanh số bán'[ProductCode]) &&
			        FACT_Sale_Voucher[isUsingDiscount] = 1))
		lineageTag: 62d48908-24c4-48f7-a1cf-e283eb7ba75b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Dso+Voucher = ```
			
			SWITCH(
			    TRUE(),
			    'FACT_Sale_Doanh số bán'[isTax] = TRUE(), BLANK(),
			    NOT ISBLANK('FACT_Sale_Doanh số bán'[Nhóm S-Star]), 
			        'FACT_Sale_Doanh số bán'[Dso] + 
			        'FACT_Sale_Doanh số bán'[DiscountAmount] + 
			        'FACT_Sale_Doanh số bán'[PromotionAmount],
			    'FACT_Sale_Doanh số bán'[Dso]
			)
			
			```
		lineageTag: f890ea19-f95e-4b4e-8e41-33a16c13274c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column isTax
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f686a780-ff43-492d-8527-a964f88698a8
		summarizeBy: none
		sourceColumn: isTax

		annotation SummarizationSetBy = Automatic

	column 'Nhóm S-Star' = related('DIM_Danh mục_Nhóm hàng'[Nhóm S-Star])
		lineageTag: d5089e17-654c-48be-a487-e5018afc4e89
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Số ngày trong tháng' =
			
			CALCULATE(
			    DISTINCTCOUNT('DIM_Danh mục_Ngày'[Date]),
			    FILTER(
			        'DIM_Danh mục_Ngày',
			        'DIM_Danh mục_Ngày'[Đầu tháng] = EARLIER( 'FACT_Sale_Doanh số bán'[StartDate] )
			    )
			)
		formatString: 0
		lineageTag: d081f769-8db1-4d5f-853d-3c39356d6895
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'FACT_Sale_Doanh số bán' = m
		mode: import
		source = ```
				let
				    Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject="cellphones-data-platform"]){[Name="cellphones-data-platform"]}[Data], "---""dataset_id=6e97d189-0524-457d-bd6e-30d5e5ad63ad""#(lf)with tax_exportBill AS (#(lf)  SELECT DISTINCT Code#(lf)FROM `cellphones-data-platform.cps_cdc_sep_hcm_dbo.Tax_ExportBill`#(lf)WHERE #(lf)CAST(_airbyte_emitted_at as date) >= '2024-09-27' #(lf)AND CAST(_airbyte_emitted_at as date) < current_date('Asia/Ho_Chi_Minh') #(lf)AND BillType = 3 #(lf)AND SignOfBillNo IN ('C25TAA', 'C25TCP')#(lf)union all #(lf)  SELECT DISTINCT Code#(lf)FROM cellphones-data-platform.cps_cdc_sep_hn_dbo.Tax_ExportBill#(lf)WHERE #(lf)CAST(_airbyte_emitted_at as date) >= '2024-09-27' #(lf)AND CAST(_airbyte_emitted_at as date) < current_date('Asia/Ho_Chi_Minh') #(lf)AND BillType = 3 #(lf)AND SignOfBillNo IN ('C25TAA', 'C25TCP')#(lf))#(lf)#(lf)SELECT#(lf)  DATETIME(CreateDate) AS CreateDate,#(lf)  Date,#(lf)  DMC3,#(lf)  AutoCode,#(lf)  ProductCode,#(lf)  ProductName,#(lf)  MethodName,#(lf)  centerid,#(lf)  StoreCode,#(lf)  Price,#(lf)  SaleEmployeeCode,#(lf)  SUM(amount) AS Dso,#(lf)  SUM(quantity) AS SL,#(lf)  IsSales AS IsSale,#(lf)  IF#(lf)    (tax.Code IS NOT NULL#(lf)        OR AutoCode IN (""SP.912THD.25.08.000244"", ""SP.15DK.25.08.000398"", ""SP.1393THD.25.08.000319"") , TRUE, FALSE) AS isTax#(lf)FROM#(lf)  `cellphones-data-platform.cps_sales_datamart.cps_cdc_sep_union_dbo_sales_transaction` sales#(lf)LEFT JOIN#(lf)  tax_exportBill tax ON sales.AutoCode = tax.Code#(lf)WHERE#(lf)  IsSales = 1#(lf)  AND IsB2B = 0#(lf)  AND DATE(CreateDate) < CURRENT_DATE()#(lf)  AND DATE(CreateDate) >= '2024-12-01'#(lf)  AND NOT ContactPhone in ('0942482682','0979453264')#(lf)  AND NOT AutoCode LIKE '%#%'#(lf)  AND NOT StoreCode IN ('HCM.KHO','HN.KHO','HN.KHOLUUTRU','HCM.KHOLUUTRU', 'HN.PKL', 'HN.DT2', 'HCM.MXTCC', 'HN.BHPK', 'HN.DT')#(lf)GROUP BY 1,2,3,4,5,6,7,8,9,10,11,14,15", null, [EnableFolding=true]),
				    #"Appended Query" = Table.Combine({Source, #"FACT_Sale_Doanh số bán_realtime"}),
				    #"Filtered Rows" = Table.SelectRows(#"Appended Query", each ([MethodName] <> "Bán B2B") and ([centerid] = 1 or [centerid] = 3759 or [centerid] = 12869)), 
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "Nhóm giá", each Number.RoundUp([Price],-3), Int64.Type),
				    #"Merged Queries" = Table.NestedJoin(#"Added Custom", {"AutoCode"}, #"Đơn không tính S-Star", {"Số phiếu"}, "Đơn không tính S-Star", JoinKind.LeftOuter),
				    #"Expanded Đơn không tính S-Star" = Table.ExpandTableColumn(#"Merged Queries", "Đơn không tính S-Star", {"S-Star"}, {"S-Star"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded Đơn không tính S-Star", {"ProductCode"}, #"S-Star_Nhóm hàng_SKU", {"SKU"}, "S-Star_Nhóm hàng_SKU", JoinKind.LeftOuter),
				    #"Expanded S-Star_Nhóm hàng_SKU" = Table.ExpandTableColumn(#"Merged Queries1", "S-Star_Nhóm hàng_SKU", {"Thi đua S-Star"}, {"Thi đua S-Star"}),
				    #"Added Custom1" = Table.AddColumn(#"Expanded S-Star_Nhóm hàng_SKU", "exp_S-Star", each if (([DMC3] = "PHỤ KIỆN IT" or [DMC3] = "PHỤ KIỆN APPLE") and [#"Thi đua S-Star"] = null) or [#"S-Star"] = 1 then 1 else null, Int64.Type),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom1",{"S-Star", "Thi đua S-Star"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns","HN.384XD","HN.360XD",Replacer.ReplaceText,{"StoreCode"})
				in
				    #"Replaced Value"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

