table FACT_GSheet_Target_Shop_Daily
	lineageTag: ef36ba07-5ff7-4713-982d-4691d003e31e

	column Miền
		dataType: string
		lineageTag: 65078d28-7e13-4e8f-993f-7ac6aa2b389b
		summarizeBy: none
		sourceColumn: Miền

		annotation SummarizationSetBy = Automatic

	column Object
		dataType: string
		lineageTag: 1facd3fb-130d-40b7-bc71-1da875aad373
		summarizeBy: none
		sourceColumn: Object

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 4c51a032-6b80-4cc6-9bdb-06dffa6ad326
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Target
		dataType: double
		formatString: #,0.00
		lineageTag: fb5010eb-5c74-43d5-9169-2be7cfd16a7d
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

	column 'Mã Kho' = ```
			
			VAR minindex_kho =
			    CALCULATE (
			        MIN ( 'DIM_Danh mục_Kho'[Index] ),
			        FILTER (
			            'DIM_Danh mục_Kho',
			            'DIM_Danh mục_Kho'[Tên kho] = EARLIER ( 'FACT_GSheet_Target_Shop_Daily'[Object] )
			        )
			    )
			VAR minindex_cuahang =
			    CALCULATE (
			        MIN ( 'DIM_Danh mục_Kho'[Index] ),
			        FILTER (
			            'DIM_Danh mục_Kho',
			            'DIM_Danh mục_Kho'[Phân loại kho] = "Kho cửa hàng"
			            && 'DIM_Danh mục_Kho'[Kho phân tích] = "Kho bình thường"            
			            && 'DIM_Danh mục_Kho'[Cửa hàng] = EARLIER ( 'FACT_GSheet_Target_Shop_Daily'[Object] )
			        )
			    )
			VAR minindex =
			    IF ( minindex_cuahang <> BLANK (), minindex_cuahang, minindex_kho )
			RETURN
			    LOOKUPVALUE ( 'DIM_Danh mục_Kho'[Mã kho], 'DIM_Danh mục_Kho'[Index], minindex )
			```
		lineageTag: 669b0b4c-fb18-4b79-a250-a004bc04f836
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: eb154cce-b859-43c3-98c6-d78469429d8d
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition FACT_GSheet_Target_Shop_Daily = m
		mode: import
		queryGroup: 'Đánh giá\Target Shop'
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vTXSTDg5uUHUVf0LUUscrFFlMcCWSBYmv6rfNO7Z3mQoxLVo4aLZJT8gBru_Q9zP_YgDoafm6EUX8F0/pub?output=xlsx"), null, true),
				    TargetDaily_SHOP_Aug24_Sheet = Source{[Item="TargetDaily_SHOP_Aug24",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(TargetDaily_SHOP_Aug24_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Shop", type text}, {"Ddate", type date}, {"DOW", Int64.Type}, {"K_DOW", type number}, {"Avg_Dso", type number}, {"ETA", type number}, {"MTD_ETA", type number}, {"Percentage_of_Target", type number}, {"Percentage_of_TargetDaily", type number}, {"Type", type text}, {"TargetDaily", type number}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Shop", "Ddate", "Type", "TargetDaily"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"Shop", "Object"}, {"Ddate", "Date"}, {"TargetDaily", "Target"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Type] <> "NoniPhone")),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows","CPS-HNO-CGI-306CG","CPS-HNO-CGI-310CG",Replacer.ReplaceText,{"Object"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","CPS-HNO-DDA-384XD","CPS-HNO-DDA-360XD",Replacer.ReplaceText,{"Object"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","CPS-HNO-DDA-ON98TH","CPS-HNO-SHOPONLINE",Replacer.ReplaceText,{"Object"}),
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Value2", {"Object"}, #"DIM_Danh mục_Phòng ban", {"Cửa hàng"}, "DIM_Danh mục_Phòng ban", JoinKind.LeftOuter),
				    #"Expanded DIM_Danh mục_Phòng ban" = Table.ExpandTableColumn(#"Merged Queries", "DIM_Danh mục_Phòng ban", {"Miền"}, {"Miền"})
				in
				    #"Expanded DIM_Danh mục_Phòng ban"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

