table 'DIM_Danh mục_Các loại chỉ số'
	excludeFromModelRefresh
	lineageTag: 2a32a526-e4bc-4667-91f0-330d89f1aa3b

	column 'Các loại chỉ số'
		dataType: string
		lineageTag: a8e2d0c4-1ac2-47ca-9320-b494f777d7a5
		summarizeBy: none
		sourceColumn: Các loại chỉ số
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Công thức tính'
		dataType: string
		lineageTag: 872e5ced-c3d4-4555-95b5-e736ee9db35e
		summarizeBy: none
		sourceColumn: Công thức tính

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: bbd398c9-295d-4894-9a01-21e663e2a3b9
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition 'DIM_Danh mục_Các loại chỉ số' = m
		mode: import
		queryGroup: 'Danh mục'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("hZDNSsNAFIVf5TJQaLHFlK67cFdQ3BjcZLKIMSShaYLpxBfoQrsQzELctmgRigVB3WQoLib4HtMn8eanNSmImxmYe+Y79xxNI6rkD74NpiP5FJgrlhGksUzmjLTJmeQxeN9vkj+hpBiajliBKd6hMQjEzAfm4OmAaoS2xWAzXUBXURpEb+/QaexKPhnB6cn5AOVWAFeRWCN+cxs31TBCyYV4RYYp+YsBI8kf3aoZCwOU9DKnuW+3CnR9F1a4U4L+lCC6CwegNY9MFhkedMrtWofFrVP2D+S5AimTdaCg7SD7iKEjPvK0WXmYIlkwcGTyxTCA5Hc4GmOdiE3vc0WfRorSs/Z67Of10ZD6xzXeX+pt1b97eNj2DYOhWGZ/+aSo/FJ8uuhd0Y1lsi4VdejeL7gWs204JlYowIegHkrXfwA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Các loại chỉ số" = _t, #"Công thức tính" = _t]),
				    #"Added Index" = Table.AddIndexColumn(Source, "Index", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

