table 'DIM_Danh mục_Shop_SMKN'
	lineageTag: 224ab604-98ba-4e0a-b70c-809455a77bc9

	column MIỀN
		dataType: string
		lineageTag: 4cd8843d-807c-4006-bbf4-a313d7ec498e
		summarizeBy: none
		sourceColumn: MIỀN

		annotation SummarizationSetBy = Automatic

	column SHOP
		dataType: string
		lineageTag: 117b0a3c-08f1-4ea8-9381-aaa867c2e7c5
		summarizeBy: none
		sourceColumn: SHOP

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: a5b337a7-5ea5-436a-be0c-5b7ed5705ffd
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: d1235f7f-19f4-4de1-a6ee-73e7157c8da2
			defaultHierarchy: LocalDateTable_4721c79d-8f41-4da5-a2ba-31b7067bf5fb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column SMKN
		dataType: string
		lineageTag: ae1be2b6-ffa9-4ae3-a502-9f3f9332243b
		summarizeBy: none
		sourceColumn: SMKN

		annotation SummarizationSetBy = Automatic

	column CuaHang_NamThang = 'DIM_Danh mục_Shop_SMKN'[SHOP] & " - " & FORMAT('DIM_Danh mục_Shop_SMKN'[StartDate], "YYYY/MM")
		lineageTag: 83d6c3a3-c49e-41aa-886e-82de6a9d47bf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'DIM_Danh mục_Shop_SMKN' = m
		mode: import
		queryGroup: 'Đánh giá'
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vTwHaFyF_TWXVJLFL98imtp7wkwVkkQR_LnmBiN0h2P6uNXh7HTWHJ_tfEf12O55RbvAmth1hD1fbkS/pub?output=xlsx"), null, true),
				    #"Shop_SM KN_YM_Sheet" = Source{[Item="Shop_SM KN_YM",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Shop_SM KN_YM_Sheet", [PromoteAllScalars=true]),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Promoted Headers", {"MIỀN", "SHOP"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Other Columns",{{"Attribute", "StartDate"}, {"Value", "SMKN"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"MIỀN", type text}, {"SHOP", type text}, {"StartDate", type date}, {"SMKN", type text}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Changed Type",{{"SMKN", Text.Upper, type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Uppercased Text", each [StartDate] >= #date(2024, 1, 1)),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows","CPS-HNO-DDA-384XD","CPS-HNO-DDA-360XD",Replacer.ReplaceText,{"SHOP"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

