table 'DIM_Danh mục_Hệ số Chỉ tiêu'
	excludeFromModelRefresh
	lineageTag: b0b39412-945e-4540-9d68-649e93b6c617

	column Tháng
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: 6b50ab4c-37fc-47f4-babd-095a71463860
		summarizeBy: none
		sourceColumn: Tháng

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Chỉ tiêu'
		dataType: string
		lineageTag: e973ce7c-b5b3-4ef3-bf7d-b25b265ed93c
		summarizeBy: none
		sourceColumn: Chỉ tiêu
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Hệ số'
		dataType: double
		formatString: 0%;-0%;0%
		lineageTag: f8b0489d-29de-4a02-97fd-f20d8d557483
		summarizeBy: sum
		sourceColumn: Hệ số

		annotation SummarizationSetBy = Automatic

	column Target
		dataType: string
		lineageTag: 16913d70-576c-482c-a6f6-cdc0c77a3505
		summarizeBy: none
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: eb370ed0-1825-4247-b835-e02d434ad3d5
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition 'DIM_Danh mục_Hệ số Chỉ tiêu' = m
		mode: import
		queryGroup: 'Danh mục'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("hVNfS8JQFP8qB8G3aXfKogIfygShMkjf1Ie5hnekdzLvhHqLiIieeuhdEQkCySgIdh8nfo/7TTrbdJbUetmFe377/TtbvZ7KkZyWUUmGqCklVZPiEzpS3EFfiimcSzFhbShVj3FGsqqGRwYQdB+BuLOY4bzlDy+3YP4oxQOj0LL8F7YHu1o61VT+5K+5DrMHpgNnOjfX7FXryoR9BQ6g4RKSN0BtsPCuqMChAqXVNclqSezoxRtxYPMbtNd3pTfhP/2tFUNCUyUk0W5nMZNizIFLb2yB3utFBGEfR9SFgRRvBpSLJzDwh1CuQAHyJN1g36cce0N9nCRXwx0pbtHuYsSA+kPWjrWi8CpJIwZDBIxPGDCCti3dXuKTyBFBwfA/4vdOWcdiZqyRDiHsN0xUvgnb//inYd+c2j7uIHSEz3c9liBZom1EOLd1lOTYlSHFsw59aveSNfRukBj9+UM7WMvIXjLHOy3s7CT7XMxwM96EQbVrdlumsyY4saS4ZnAgvVcDP+U8bnJ5VUHdfz7tIEXQwbQHR+VaZc2aVzdS40/2CBfUHxk0OIK+u66+WmLzCw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Tháng = _t, #"Chỉ tiêu" = _t, #"Hệ số" = _t, Target = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Tháng", type date}, {"Hệ số", Percentage.Type}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Index", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

