table 'DIM_Danh mục_Đánh giá'
	excludeFromModelRefresh
	lineageTag: 75a67b21-b41b-45f3-8b39-50948899e2fb

	column Index
		dataType: string
		lineageTag: b0a67e2e-498a-4850-97cf-95da3d49cd93
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column 'Đánh giá'
		dataType: string
		lineageTag: e82c932c-fe8b-406f-9a18-7facdff089e4
		summarizeBy: none
		sourceColumn: Đánh giá

		annotation SummarizationSetBy = Automatic

	column 'Đánh giá cuối cùng'
		dataType: string
		lineageTag: a2d52ce0-175e-4638-9f41-4ddd417de155
		summarizeBy: none
		sourceColumn: Đánh giá cuối cùng
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Điểm quy đổi'
		dataType: int64
		formatString: 0
		lineageTag: 58070e28-9d76-48d6-a948-d48953a2a9e9
		summarizeBy: sum
		sourceColumn: Điểm quy đổi

		annotation SummarizationSetBy = Automatic

	partition 'DIM_Danh mục_Đánh giá' = m
		mode: import
		queryGroup: 'Danh mục'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUYoofbhraYlC8cNd65MVSkorH+5uL1E4MvHh7omZQNkjEx7uWlgCZJgoxepEKxkBWSFAqRJkKWOwlDGQ5Z1xeCGE2pKXDjIEosAIrMAEJHN4ZS4WBYZgBaZAlvPDXYvzMhSSDy/Mx6LOQCk2FgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Index = _t, #"Đánh giá cuối cùng" = _t, #"Đánh giá" = _t, #"Điểm quy đổi" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Điểm quy đổi", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

