table FACT_BQ_Target_Shop
	excludeFromModelRefresh
	lineageTag: 04366cf8-b545-4924-bde6-97c006d14461

	column Miền
		dataType: string
		lineageTag: 560005a1-77bc-465a-98e6-07ba11e40bef
		summarizeBy: none
		sourceColumn: Miền

		annotation SummarizationSetBy = Automatic

	column 'Ngày bắt đầu'
		dataType: dateTime
		formatString: Short Date
		lineageTag: d8279c14-55c2-47e0-a4a7-925f1bda78e6
		summarizeBy: none
		sourceColumn: Ngày bắt đầu

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ngày kết thúc'
		dataType: dateTime
		formatString: Short Date
		lineageTag: bed64949-914b-4a2d-a088-664322b8ca6b
		summarizeBy: none
		sourceColumn: Ngày kết thúc

		variation Variation
			isDefault
			relationship: d44a6b85-8f74-44a6-a31f-85e546e43843
			defaultHierarchy: LocalDateTable_7981910b-21ed-4aa2-b870-68d9b417daa5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Shop
		dataType: string
		lineageTag: 461eda86-aa83-4327-af17-84bcc78645db
		summarizeBy: none
		sourceColumn: Shop

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 8cee913f-7e73-4218-96fc-6ed818d23920
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Target
		dataType: double
		lineageTag: f98fc58f-6dd4-4a08-9576-6429a16410d7
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Mã Kho' =
			
			VAR minindex_kho =
			    CALCULATE (
			        MIN ( 'DIM_Danh mục_Kho'[Index] ),
			        FILTER (
			            'DIM_Danh mục_Kho',
			            'DIM_Danh mục_Kho'[Tên kho] = EARLIER ( 'FACT_BQ_Target_Shop'[Shop] )
			        )
			    )
			VAR minindex_cuahang =
			    CALCULATE (
			        MIN ( 'DIM_Danh mục_Kho'[Index] ),
			        FILTER (
			            'DIM_Danh mục_Kho',
			            'DIM_Danh mục_Kho'[Phân loại kho] = "Kho cửa hàng"
			            && 'DIM_Danh mục_Kho'[Kho phân tích] = "Kho bình thường"
			            && 'DIM_Danh mục_Kho'[Cửa hàng] = EARLIER ( 'FACT_BQ_Target_Shop'[Shop] )
			        )
			    )
			VAR minindex =
			    IF ( minindex_cuahang <> BLANK (), minindex_cuahang, minindex_kho )
			RETURN
			    LOOKUPVALUE ( 'DIM_Danh mục_Kho'[Mã kho], 'DIM_Danh mục_Kho'[Index], minindex )
		lineageTag: 40d4e5a9-4099-487f-a096-6a9ae63fd0b7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition FACT_BQ_Target_Shop = m
		mode: import
		queryGroup: 'Đánh giá\Target Shop'
		source =
				let
				    Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject="cellphones-data-platform"]){[Name="cellphones-data-platform"]}[Data], "---""dataset_id=6e97d189-0524-457d-bd6e-30d5e5ad63ad""#(lf)SELECT #(lf)       CASE t.CenterId#(lf)           WHEN 3759 THEN 'Miền Bắc'#(lf)           WHEN 12869 THEN 'Miền Nam'#(lf)           ELSE null#(lf)       END AS `Miền`,#(lf)       DATE(t.year, t.month, 1) AS `Ngày bắt đầu`,#(lf)       LAST_DAY(DATE(t.year, t.month, 1), MONTH) AS `Ngày kết thúc`,#(lf)       b.Name AS Shop,#(lf)       CASE TYPE#(lf)           WHEN 'TotalSales' THEN 'DSO TARGET'#(lf)           WHEN 'SideInstruments' THEN 'BÁN KÈM TARGET'#(lf)           WHEN 'AccessoryGroup1' THEN 'PK1 TARGET'#(lf)           WHEN 'AccessoryGroup2' THEN 'PK2 TARGET'#(lf)           WHEN 'AndroidTTQuantity' THEN 'Android'#(lf)           WHEN 'NonIphoneQuantity' THEN 'NoniPhone'#(lf)       END AS Type,#(lf)       Target,    #(lf)FROM `cellphones-data-platform.cps_mssql_HaraData_dwh.Shared_TargetSalesRevenue` #(lf)UNPIVOT(Target FOR TYPE IN (TotalSales, SideInstruments, AccessoryGroup1, AccessoryGroup2, AndroidTTQuantity, NonIphoneQuantity))t#(lf)JOIN `cellphones-data-platform.cps_cdc_sep_hcm_dbo.ERP_SubBranch` b ON t.BranchId = b.Id#(lf)  WHERE Target > 0 AND t.CenterId IN (3759, 12869) AND t.YEAR >= 2024", null, [EnableFolding=true]),
				    #"Replaced Value" = Table.ReplaceValue(Source,"CPS-HNO-DDA-384XD","CPS-HNO-DDA-360XD",Replacer.ReplaceText,{"Shop"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

