table 'FACT_Đánh giá SM'
	lineageTag: c8d2f177-9f21-49d9-b393-d07386f5633d

	column MIỀN
		dataType: string
		lineageTag: ada16ecd-6568-4259-921a-80bfe022c8a8
		summarizeBy: none
		sourceColumn: MIỀN

		annotation SummarizationSetBy = Automatic

	column MNV
		dataType: string
		lineageTag: 170b24f2-5ae5-4fcc-ad5f-6be5bab69cd6
		summarizeBy: none
		sourceColumn: MNV

		annotation SummarizationSetBy = Automatic

	column SM/SUP
		dataType: string
		lineageTag: d4abd8ca-f626-42e9-8ec1-09b1238c8292
		summarizeBy: none
		sourceColumn: SM/SUP

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: eaa5f18d-130e-46dc-beae-346e8eed7a04
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: 67638662-da77-4df9-b893-7e6ea6900d44
			defaultHierarchy: LocalDateTable_73350579-98fb-41ee-b414-adbb034c9690.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SHOP
		dataType: string
		lineageTag: 89f89681-be88-4edd-9271-1ff69a9a25f2
		summarizeBy: none
		sourceColumn: SHOP

		annotation SummarizationSetBy = Automatic

	column CuaHang_NamThang = 'FACT_Đánh giá SM'[SHOP] & " - " & FORMAT('FACT_Đánh giá SM'[StartDate], "YYYY/MM")
		lineageTag: 21ff4fb6-c53a-45a1-89e4-4b667dffc7d8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Ma_TenSM = 'FACT_Đánh giá SM'[MNV] &" - "& 'FACT_Đánh giá SM'[SM/SUP]
		lineageTag: 72b74210-3216-4a95-9e8a-23b04bfee5f2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Quý = RELATED('DIM_Danh mục_Ngày'[Năm/Quý])
		lineageTag: efc4e396-c079-47fe-aa11-56023e919e4f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'FACT_Đánh giá SM' = m
		mode: import
		queryGroup: 'Đánh giá'
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vTwHaFyF_TWXVJLFL98imtp7wkwVkkQR_LnmBiN0h2P6uNXh7HTWHJ_tfEf12O55RbvAmth1hD1fbkS/pub?output=xlsx"), null, true),
				    Shop_SM_YM_Sheet = Source{[Item="Shop_SM_YM",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Shop_SM_YM_Sheet, [PromoteAllScalars=true]),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Promoted Headers", {"MIỀN", "MNV", "SM/SUP"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Other Columns",{{"Attribute", "StartDate"}, {"Value", "SHOP"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"MIỀN", type text}, {"MNV", type text}, {"SM/SUP", type text}, {"StartDate", type date}, {"SHOP", type text}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Changed Type",{{"SM/SUP", Text.Upper, type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Uppercased Text", each [StartDate] >= #date(2024, 1, 1) and ([SHOP] <> "")),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each true),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows1","CPS-HNO-DDA-384XD","CPS-HNO-DDA-360XD",Replacer.ReplaceText,{"SHOP"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

