table 'Kết quả đánh giá Shop'
	lineageTag: 9c92ac03-bbfb-4f71-82d6-7733abb1db78

	column 'Điểm quy đổi' = RELATED('DIM_Danh mục_Hệ số SizeShop'[Hệ số])
		formatString: 0
		lineageTag: 9320fc7c-5a52-4fc6-869f-018974896c2a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Đạt_Tổng = 'Kết quả đánh giá Shop'[Tổng chỉ tiêu đạt] & " | " & 'Kết quả đánh giá Shop'[Slg chỉ tiêu đánh giá]
		lineageTag: 41966314-8a9f-4c5b-9c8d-663b9ec4fb13
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CuaHang_NamThang = 'Kết quả đánh giá Shop'[Cửa hàng] & " - " & FORMAT('Kết quả đánh giá Shop'[Tháng], "YYYY/MM")
		lineageTag: e6b7787b-41e3-4d81-b54c-6eac46877b1a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column AM_NamThang = 'Kết quả đánh giá Shop'[AM] & " - " & FORMAT('Kết quả đánh giá Shop'[Tháng], "YYYY/MM")
		lineageTag: cb40803c-286f-48bd-81e7-8fc120b24660
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Quý = RELATED('DIM_Danh mục_Ngày'[Năm/Quý])
		lineageTag: 73722df0-b2cb-4cee-8947-2fddd4bd01a3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column SizeShop = RELATED('DIM_Danh mục_Phòng ban'[Size])
		lineageTag: 8941ee8d-c4e9-4316-a18b-87b99435a709
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Điểm SizeShop' = RELATED('DIM_Danh mục_Hệ số SizeShop'[Hệ số]) * 'Kết quả đánh giá Shop'[Điểm quy đổi]
		lineageTag: 583e4ec2-5e74-455c-a110-c51e244ee275
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Score_heso =
			
			DIVIDE (
			    SUMX (
			        FILTER (
			            'Kết quả đánh giá Shop',
			            'Kết quả đánh giá Shop'[Miền] = EARLIER('Kết quả đánh giá Shop'[Miền]) &&
			            'Kết quả đánh giá Shop'[Tháng] = EARLIER('Kết quả đánh giá Shop'[Tháng]) &&
			            'Kết quả đánh giá Shop'[AM] = EARLIER('Kết quả đánh giá Shop'[AM])
			        ),
			        'Kết quả đánh giá Shop'[Kds/Score] * 'Kết quả đánh giá Shop'[Điểm quy đổi]
			    ),
			    SUMX (
			        FILTER (
			            'Kết quả đánh giá Shop',
			            'Kết quả đánh giá Shop'[Miền] = EARLIER('Kết quả đánh giá Shop'[Miền]) &&
			            'Kết quả đánh giá Shop'[Tháng] = EARLIER('Kết quả đánh giá Shop'[Tháng]) &&
			            'Kết quả đánh giá Shop'[AM] = EARLIER('Kết quả đánh giá Shop'[AM])
			        ),
			        'Kết quả đánh giá Shop'[Điểm quy đổi]
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: deddc24f-c31e-4c0e-8dc3-7e0171bac5e2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Tổng chỉ tiêu đạt_heso' = ```
			
			VAR 
			_z = 
			DIVIDE (
			    SUMX (
			        FILTER (
			            'Kết quả đánh giá Shop',
			            'Kết quả đánh giá Shop'[Miền] = EARLIER('Kết quả đánh giá Shop'[Miền]) &&
			            'Kết quả đánh giá Shop'[Tháng] = EARLIER('Kết quả đánh giá Shop'[Tháng]) &&
			            'Kết quả đánh giá Shop'[AM] = EARLIER('Kết quả đánh giá Shop'[AM])
			        ),
			        'Kết quả đánh giá Shop'[Tổng chỉ tiêu đạt] * 'Kết quả đánh giá Shop'[Điểm quy đổi]
			    ),
			    SUMX (
			        FILTER (
			            'Kết quả đánh giá Shop',
			            'Kết quả đánh giá Shop'[Miền] = EARLIER('Kết quả đánh giá Shop'[Miền]) &&
			            'Kết quả đánh giá Shop'[Tháng] = EARLIER('Kết quả đánh giá Shop'[Tháng]) &&
			            'Kết quả đánh giá Shop'[AM] = EARLIER('Kết quả đánh giá Shop'[AM])
			        ),
			        'Kết quả đánh giá Shop'[Điểm quy đổi]
			    )
			)
			RETURN
			ROUND(_z,0)
			```
		lineageTag: a936ee46-fcb0-4830-99eb-cddc6e0e787f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% Target Dso'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a5d75682-1f07-4d8e-8091-e712af0ee196
		summarizeBy: sum
		sourceColumn: % Target Dso

		annotation SummarizationSetBy = Automatic

	column '% Target lượt tải app'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 53f7fa5a-3f7f-49cf-9306-cc816fd9680b
		summarizeBy: sum
		sourceColumn: % Target lượt tải app

		annotation SummarizationSetBy = Automatic

	column '% Target năng suất định biên'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8ef41b8b-d1c5-4bf5-9f40-0d8c15f887ca
		summarizeBy: sum
		sourceColumn: % Target năng suất định biên

		annotation SummarizationSetBy = Automatic

	column '% Target sử dụng ESL'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4819f32d-c6e4-4171-8a32-3e4f6631bdd0
		summarizeBy: sum
		sourceColumn: % Target sử dụng ESL

		annotation SummarizationSetBy = Automatic

	column '% Target tham gia đào tạo'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0a238f45-38cc-4499-b4fd-6b126637ebba
		summarizeBy: sum
		sourceColumn: % Target tham gia đào tạo

		annotation SummarizationSetBy = Automatic

	column '% Target thu thập KHTN'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0846e5d8-48f5-418f-8d7b-e2e0674c932b
		summarizeBy: sum
		sourceColumn: % Target thu thập KHTN

		annotation SummarizationSetBy = Automatic

	column '% Target thất thoát hàng hóa'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: dd870c9a-36e8-4ad1-a683-ffd540f19ec8
		summarizeBy: sum
		sourceColumn: % Target thất thoát hàng hóa

		annotation SummarizationSetBy = Automatic

	column '% Target trễ đơn giao hàng'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5623db1b-d330-4f0a-bcc0-d76c658e092b
		summarizeBy: sum
		sourceColumn: % Target trễ đơn giao hàng

		annotation SummarizationSetBy = Automatic

	column '% Target turnover rate'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c40704d7-838f-42da-b22b-b722cd33adbe
		summarizeBy: sum
		sourceColumn: % Target turnover rate

		annotation SummarizationSetBy = Automatic

	column '% Target tư vấn smember'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8a570b08-a2c2-4a3f-8a70-0a9f53781cbb
		summarizeBy: sum
		sourceColumn: % Target tư vấn smember

		annotation SummarizationSetBy = Automatic

	column AM
		dataType: string
		lineageTag: 4be3f5f4-a1eb-4156-9efa-781ac018ffdd
		summarizeBy: none
		sourceColumn: AM

		annotation SummarizationSetBy = Automatic

	column 'Cửa hàng'
		dataType: string
		lineageTag: a1faad9b-48d6-4ae3-9ed1-783c159108f5
		summarizeBy: none
		sourceColumn: Cửa hàng

		annotation SummarizationSetBy = Automatic

	column Kds/Score
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2d96b3c8-81b8-4fbd-9fb8-e28300400b5e
		summarizeBy: sum
		sourceColumn: Kds/Score

		annotation SummarizationSetBy = Automatic

	column Miền
		dataType: string
		lineageTag: d7df7f4a-f2a0-4669-8c6f-16bcc6ad2ec5
		summarizeBy: none
		sourceColumn: Miền

		annotation SummarizationSetBy = Automatic

	column 'Slg chỉ tiêu đánh giá'
		dataType: int64
		formatString: 0
		lineageTag: 55cc2133-33a2-494e-800e-e5d447a7557e
		summarizeBy: sum
		sourceColumn: Slg chỉ tiêu đánh giá

		annotation SummarizationSetBy = Automatic

	column 'Tổng chỉ tiêu đạt'
		dataType: int64
		formatString: 0
		lineageTag: bcafe69c-883d-4a9a-a36d-59c4f08ea28a
		summarizeBy: sum
		sourceColumn: Tổng chỉ tiêu đạt

		annotation SummarizationSetBy = Automatic

	column 'Xếp hạng cuối cùng'
		dataType: int64
		formatString: 0
		lineageTag: a3e4320a-aa8c-4214-9e38-00fa117174ed
		summarizeBy: sum
		sourceColumn: Xếp hạng cuối cùng

		annotation SummarizationSetBy = Automatic

	column 'Đánh giá cuối cùng'
		dataType: string
		lineageTag: 3559c4fd-b26d-49c1-b9c4-bf5a200acd99
		summarizeBy: none
		sourceColumn: Đánh giá cuối cùng

		annotation SummarizationSetBy = Automatic

	column Tháng
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1a109bdb-c0c2-4ccf-b786-06313a7a133d
		summarizeBy: none
		sourceColumn: Tháng

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column '% Target thành công đơn Online'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e5e40e9c-ef0b-475c-99c1-e99f1c6f49c6
		summarizeBy: sum
		sourceColumn: % Target thành công đơn Online

		annotation SummarizationSetBy = Automatic

	partition 'Kết quả đánh giá Shop' = m
		mode: import
		queryGroup: 'Đánh giá\Kết quả Shop'
		source =
				let
				    Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject="cellphones-data-platform"]){[Name="cellphones-data-platform"]}[Data], "---""dataset_id=6e97d189-0524-457d-bd6e-30d5e5ad63ad""#(lf)#(lf)SELECT#(lf)  * EXCEPT (#(lf)    id,#(lf)    record_id,#(lf)    last_modified_time,#(lf)    created_time,#(lf)    last_modified_by,#(lf)    created_by,#(lf)    thang#(lf)  ),#(lf)  DATE(TIMESTAMP_MILLIS(thang), ""Asia/Ho_Chi_Minh"") AS thang#(lf)FROM `cellphones-data-platform.cps_larkbase.danh_gia_nlvh`", null, [EnableFolding=true]),
				    #"Filtered Rows" = Table.SelectRows(Source, each true),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"thang", "Tháng"}, {"danh_gia_cuoi_cung", "Đánh giá cuối cùng"}, {"xep_hang_cuoi_cung", "Xếp hạng cuối cùng"}, {"tong_chi_tieu_dat", "Tổng chỉ tiêu đạt"}, {"target_tu_van_smember", "Target tư vấn smember"}, {"slg_chi_tieu_danh_gia", "Slg chỉ tiêu đánh giá"}, {"mien", "Miền"}, {"kds_score", "Kds/Score"}, {"cua_hang", "Cửa hàng"}, {"am", "AM"}, {"_target_tu_van_smember", "% Target tư vấn smember"}, {"_target_turnover_rate", "% Target turnover rate"}, {"_target_tre_don_giao_hang", "% Target trễ đơn giao hàng"}, {"_target_that_thoat_hang_hoa", "% Target thất thoát hàng hóa"}, {"_target_thu_thap_khtn", "% Target thu thập KHTN"}, {"_target_tham_gia_dao_tao", "% Target tham gia đào tạo"}, {"_target_su_dung_esl", "% Target sử dụng ESL"}, {"_target_nang_suat_dinh_bien", "% Target năng suất định biên"}, {"_target_dso", "% Target Dso"}, {"_target_luot_tai_app", "% Target lượt tải app"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"% Target Dso", Percentage.Type}, {"% Target lượt tải app", Percentage.Type}, {"% Target năng suất định biên", Percentage.Type}, {"% Target sử dụng ESL", Percentage.Type}, {"% Target tham gia đào tạo", Percentage.Type}, {"% Target thu thập KHTN", Percentage.Type}, {"% Target thất thoát hàng hóa", Percentage.Type}, {"% Target trễ đơn giao hàng", Percentage.Type}, {"% Target turnover rate", Percentage.Type}, {"% Target tư vấn smember", Percentage.Type}, {"Target tư vấn smember", Percentage.Type}, {"Kds/Score", Percentage.Type}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type",{{"_target_thanh_cong_don_online", "% Target thành công đơn Online"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns1",{"Target tư vấn smember"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

