table Measure
	lineageTag: 3b27c585-6dc4-49b3-b4b3-2191bd6a8ff0

	measure Dso =
			
			CALCULATE(
			    SUM( 'FACT_Sale_Doanh số bán'[Dso] ),
			    FILTER(
			        'FACT_Sale_Doanh số bán',
			        'FACT_Sale_Doanh số bán'[Check online+B2B] = 0
			    )
			)
		displayFolder: 2. Chỉ tiêu
		lineageTag: d52e78ee-b5d7-4f5e-b17c-272f13c827cc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Slg =
			
			CALCULATE(
			    SUM( 'FACT_Sale_Doanh số bán'[SL] ),
			    FILTER(
			        'FACT_Sale_Doanh số bán',
			        'FACT_Sale_Doanh số bán'[Check online+B2B] = 0
			    )
			)
		displayFolder: 2. Chỉ tiêu
		lineageTag: 418a417e-a964-4e26-afa8-cc53c29bfd95

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Số cửa hàng' = DISTINCTCOUNT('FACT_Đánh giá Shop'[SHOP])
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: 33745137-e4c8-427c-bfb8-5bdbd8a0ba80

	measure 'Số quản lý' = COUNTROWS(SUMMARIZE(AM_SM_Current_Month, AM_SM_Current_Month[SM/SUP]))
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: 905d31d4-9b98-486c-b841-9881f292ada0

	measure 'Số AM' = COUNTROWS(SUMMARIZE(FILTER('FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[AM_DIM] <> "NONE"), 'FACT_Đánh giá Shop'[AM_DIM]))
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: 1d108403-b227-45a6-ab71-f4db69231b44

	measure 'Target Dso' = ```
			
			VAR target =
			    CALCULATE (
			        SUM ( 'FACT_GSheet_Target_Shop_Daily'[Target] ),
			        'FACT_GSheet_Target_Shop_Daily'[Type] = "DSO TARGET"
			    )
			VAR dso_iP17 =
			    CALCULATE (
			        [Dso],
			        FILTER (
			            'FACT_Sale_Doanh số bán',
			            CONTAINSSTRING ( 'FACT_Sale_Doanh số bán'[ProductCode], "APP-IP17" )
			            || CONTAINSSTRING ( 'FACT_Sale_Doanh số bán'[ProductCode], "APP-IP-AIR" )
			        ),
			        FILTER (
			            'FACT_Sale_Doanh số bán',
			            'FACT_Sale_Doanh số bán'[Date] >= DATE ( 2025, 9, 19 )
			            && 'FACT_Sale_Doanh số bán'[Date] <= DATE ( 2025, 9, 24 )
			        )
			    )
			RETURN
			    target + dso_iP17
			
			```
		displayFolder: 2. Chỉ tiêu
		lineageTag: 1de6b6cc-30c6-45ed-9907-7be8f62aa43d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Target Dso' = DIVIDE([Dso], [Target Dso])
		displayFolder: 2. Chỉ tiêu
		lineageTag: 36ab60b6-2778-42f7-9dcf-e3d08b88394d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dso Laptop' = ```
			
			VAR t8_25 = 
			CALCULATE(
			    [Dso],
			    FILTER(
			        'FACT_Sale_Doanh số bán',
			        'FACT_Sale_Doanh số bán'[DMC3] IN {"LAPTOP CTM", "MACBOOK CTM","LAPTOP CŨ", "MACBOOK CŨ"}
			    )
			)
			VAR nomal = 
			CALCULATE(
			    [Dso],
			    FILTER(
			        'FACT_Sale_Doanh số bán',
			        'FACT_Sale_Doanh số bán'[DMC3] IN {"LAPTOP CTM", "MACBOOK CTM"}
			    )
			)
			
			RETURN
			IF(SELECTEDVALUE('DIM_Danh mục_Ngày'[Date]) >= DATE(2025,8,1),t8_25,nomal)
			```
		displayFolder: 2. Chỉ tiêu
		lineageTag: 4e9e8343-65c1-49be-8c16-58c4c9efec6a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TurnoverRate =
			
			VAR _zMonth =
			    MAX ( 'DIM_Danh mục_Ngày'[Tháng] )
			VAR _zYear =
			    MAX ( 'DIM_Danh mục_Ngày'[Năm] )
			
			VAR _zEmployees =
			    CALCULATE ( [Nhân sự còn lại], 'DIM_Danh mục_Nhân viên'[IsIncludedInRate] = TRUE )
			
			VAR _zPrevEmployees =
			    CALCULATE (
			        [Nhân sự còn lại],
			        'DIM_Danh mục_Nhân viên'[IsIncludedInRate] = TRUE,
			        DATEADD ( 'DIM_Danh mục_Ngày'[Date], -1, MONTH )
			    )
			
			VAR _zBaseEmployees =
			    CALCULATE ( [Nhân sự còn lại], 'DIM_Danh mục_Nhân viên'[IsIncludedInRate] = TRUE )
			        - CALCULATE ( [Nhân sự mới], 'DIM_Danh mục_Nhân viên'[IsIncludedInRate] = TRUE )
			        + CALCULATE ( [Nhân sự rời đi], 'DIM_Danh mục_Nhân viên'[IsIncludedInRate] = TRUE )
			
			VAR _zAvgEmployees = ( _zEmployees + _zPrevEmployees ) / 2
			VAR _zAvgBaseEmployees = ( _zEmployees + _zBaseEmployees ) / 2
			
			-- Tính nhân sự rời đi có weighting theo loại nhân viên
			VAR _zWeightedLeavers =
			    SUMX (
			        FILTER ( 'DIM_Danh mục_Nhân viên', 'DIM_Danh mục_Nhân viên'[IsIncludedInRate] = TRUE ),
			        VAR _leavers = [Nhân sự rời đi]
			        VAR _weight =
			            SWITCH (
			                TRUE (),
			                'DIM_Danh mục_Nhân viên'[IsProbation] = "Thủ việc", 0.5,
			                1
			            )
			        RETURN _leavers * _weight
			    )
			
			-- Tính cho cả năm (nếu không lọc theo tháng)
			VAR _zReEmployees =
			    SUMX (
			        VALUES ( 'DIM_Danh mục_Ngày'[Tháng] ),
			        CALCULATE ( _zWeightedLeavers )
			    )
			
			VAR _zAvgReEmployees =
			    AVERAGEX (
			        VALUES ( 'DIM_Danh mục_Ngày'[Tháng] ),
			        CALCULATE ( [Nhân sự còn lại], 'DIM_Danh mục_Nhân viên'[IsIncludedInRate] = TRUE )
			    )
			
			RETURN
			    // IF (
			    //     HASONEVALUE ( 'DIM_Danh mục_Ngày'[Tháng] ),
			    //     IF (
			    //         _zYear = 2022 && _zMonth = 1,
			    //         MIN ( DIVIDE ( _zWeightedLeavers, _zAvgBaseEmployees, BLANK () ), 1 ),
			    //         MIN ( DIVIDE ( _zWeightedLeavers, _zAvgEmployees, BLANK () ), 1 )
			    //     ),
			    //     MIN ( DIVIDE ( _zReEmployees, _zAvgReEmployees ), 1 )
			    // )
			_zWeightedLeavers
		displayFolder: 2. Chỉ tiêu
		lineageTag: abe48741-7601-4498-a64b-2c935cc18498

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Dso_S-Star =
			
			var nhomchinh =
			CALCULATE (
			    [Dso+voucher],
			    FILTER (
			        'DIM_Danh mục_Nhóm hàng',
			        'DIM_Danh mục_Nhóm hàng'[Thi đua S-Star] = 1
			        && 'DIM_Danh mục_Nhóm hàng'[Hệ số thi đua phụ kiện] = BLANK()
			    ),
			    FILTER (
			        'FACT_Sale_Doanh số bán',
			        'FACT_Sale_Doanh số bán'[exp_S-Star] = BLANK()
			    )
			)
			var nhomphu =
			CALCULATE (
			    [Dso+voucher],
			    FILTER (
			        'DIM_Danh mục_Nhóm hàng',
			        'DIM_Danh mục_Nhóm hàng'[Thi đua S-Star] = 1
			        && 'DIM_Danh mục_Nhóm hàng'[Hệ số thi đua phụ kiện] = 0.3
			    ),
			    FILTER (
			        'FACT_Sale_Doanh số bán',
			        'FACT_Sale_Doanh số bán'[exp_S-Star] = BLANK()
			    )
			)
			return nhomchinh + nhomphu*0.3
		displayFolder: 2. Chỉ tiêu
		lineageTag: 8e69801f-3ec7-4d89-beb3-80488f5f2200

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Dso_S-Star_Base = ```
			
			SUMX(
			    FILTER(
			        'FACT_Sale_Doanh số bán',
			        'FACT_Sale_Doanh số bán'[exp_S-Star] = BLANK()
			        && ISBLANK(RELATED('D_Sản phẩm'[S-Star_exp]))
			        && NOT(ISBLANK('FACT_Sale_Doanh số bán'[Dso+Voucher]))
			    ),
			    VAR _ngayban = 'FACT_Sale_Doanh số bán'[Date]
			    VAR _store = 'FACT_Sale_Doanh số bán'[Shop]
			    VAR _nhomhang = 'FACT_Sale_Doanh số bán'[DMC3]
			
			    VAR _heso =
			        CALCULATE(
			            MAX('Heso_ThiDua'[he_so_thi_dua_phu_kien]),
			            FILTER(
			                'Heso_ThiDua',
			                'Heso_ThiDua'[ngay_bat_dau] <= _ngayban &&
			                'Heso_ThiDua'[ngay_ket_thuc] >= _ngayban &&
			                'Heso_ThiDua'[nhom_hang] = _nhomhang
			            )
			        )
			    RETURN 'FACT_Sale_Doanh số bán'[Dso+Voucher] * _heso
			)
			
			```
		displayFolder: 2. Chỉ tiêu
		lineageTag: 8e098e16-aefd-4068-a778-a86b688a470b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dso_S-Star %' = ```
			
			VAR dso_base_all = 
			    CALCULATE (
			        [Dso_S-Star_Base],
			        ALL ( 'DIM_Danh mục_Nhóm hàng' )
			    )
			RETURN 
			    DIVIDE (
			        [Dso_S-Star],
			        dso_base_all,
			        BLANK ()
			    )
			```
		displayFolder: 2. Chỉ tiêu
		lineageTag: af52dc0a-9724-41c8-9cb1-ab572eaecd7e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dso_S-Star % qd' =
			
			[Dso_S-Star %] * MAX(1, [% Target Dso])
		displayFolder: 2. Chỉ tiêu
		lineageTag: 9871d3ac-a09a-447c-977b-c7a6eac42a23

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Slg Bán máy' =
			
			CALCULATE (
			    [Slg],
			    FILTER (
			        'DIM_Danh mục_Nhóm hàng',
			        'DIM_Danh mục_Nhóm hàng'[NhomHang_isMay] = 1
			        && NOT 'DIM_Danh mục_Nhóm hàng'[Nhóm hàng] IN {"NOKIA CTM", "MASSTEL CTM", "VẬT TƯ ĐIỆN TỬ", "MOBELL CTM", "ITEL CTM", "VIETTEL CTM", "KHÁC - CTM"}
			    )
			)
		displayFolder: 2. Chỉ tiêu
		lineageTag: ba332f96-a279-4f66-a2c8-9b616623984b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Target Slg bán' =
			
			DIVIDE(
			    [Slg Bán máy],
			    [Target Slg bán]
			)
		displayFolder: 2. Chỉ tiêu
		lineageTag: ba2f072e-f257-42e8-bdb8-528e9b0c0ccd

	measure 'Target Slg bán' = SUM(FACT_GSheet_Target_Shop_Daily[Target])
		displayFolder: 2. Chỉ tiêu
		lineageTag: 41b6c7c8-8923-4cee-81ce-95467ee25cc4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Slg SPTT' =
			
			CALCULATE (
			    [Slg],
			    FILTER (
			        'FACT_Sale_Doanh số bán',
			        'FACT_Sale_Doanh số bán'[SPTT_Model] <> BLANK()
			    )
			)
		displayFolder: 2. Chỉ tiêu
		lineageTag: e347b36d-2020-42a2-97bf-8d214c598930

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RunRate =
			
			var songay = COUNTROWS('DIM_Danh mục_Ngày')
			var songaythuchien = COUNTROWS(FILTER ('DIM_Danh mục_Ngày', 'DIM_Danh mục_Ngày'[Ngày_IsActive] = 1))
			return
			DIVIDE (
			    songay,
			    songaythuchien
			)
		displayFolder: 2. Chỉ tiêu
		lineageTag: 61c44f30-759b-4bb0-91ee-af226424cee8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Thời gian cập nhật' =
			
			CALCULATE(MAX( LastUpdate[_lastUpdate_calculate] ), ALL())
		formatString: Short Date
		displayFolder: 2. Chỉ tiêu
		lineageTag: 8b14362f-d9f3-45a0-9963-f1c5594b4c86

	measure 'Số CH đạt' =
			
			CALCULATE(
			    DISTINCTCOUNT('FACT_Đánh giá Shop'[SHOP]),
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[Score] >= 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: d6268a0f-e7c7-4be2-9791-9ddb5cade929

	measure 'Số CH ko đạt' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[Score] < 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: 184652c0-f657-4367-a075-4c92221bc1fa

	measure 'Số CH đạt thu thập KHTN' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target thu thập KHTN] >= 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: e8c8541b-636d-4418-a48e-c6f3f3222103

	measure 'Số CH ko thu thập KHTN' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target thu thập KHTN] < 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: 56680697-083b-437a-bf63-0f5bd3900de3

	measure 'Số CH đạt lượt tải app' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target lượt tải app] >= 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: a3a211b5-d15e-49e2-ba9e-014379e91326

	measure 'Số CH ko lượt tải app' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target lượt tải app] < 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: 680daa98-d44b-41a3-8995-98e34d039d94

	measure 'Số CH đạt trễ đơn giao hàng' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target trễ đơn giao hàng] >= 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: a5ab6f98-4ddd-45fe-a2d2-7e8fc40af082

	measure 'Số CH ko trễ đơn giao hàng' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target trễ đơn giao hàng] < 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: 59e5a1a3-78cb-4a31-9744-88b71247679c

	measure 'Số CH đạt năng suất định biên' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target năng suất định biên] >= 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: 04dda77e-9f3c-4ee6-9797-0540e0e3f990

	measure 'Số CH ko năng suất định biên' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target năng suất định biên] < 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: 381eb6b3-2899-42d5-8b42-ddbd34854e7b

	measure 'Số CH đạt thành công đơn Online' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target thành công đơn Online] >= 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: 9e2c8d8c-8ba0-4806-84dd-67ff143b94cb

	measure 'Số CH ko thành công đơn Online' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target thành công đơn Online] < 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: 22a5d875-f65b-410a-ae7e-68289dbd4ebd

	measure 'Số CH đạt tư vấn smember' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target tư vấn smember] >= 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: bcd5389d-2996-4517-a1f3-3fe5ae0b2192

	measure 'Số CH ko tư vấn smember' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target tư vấn smember] < 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: 83a822cf-b35f-4430-8d3e-3118b1813671

	measure 'Cửa hàng' = if(HASONEVALUE('DIM_Danh mục_Phòng ban'[Cửa hàng]), VALUES('DIM_Danh mục_Phòng ban'[Cửa hàng]), BLANK())
		displayFolder: 2. Chỉ tiêu
		lineageTag: 53d23b54-6a22-486c-9266-492aa7887bda

	measure 'Số CH đạt turnover rate' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target turnover rate] >= 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: 50708c09-f17a-429f-a645-efdc4fdb7f52

	measure 'Số CH ko turnover rate' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target turnover rate] < 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: fe176a98-6a8d-4fa4-bbdf-8f5b56683689

	measure '% Số CH đạt' = DIVIDE([Số CH đạt], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: 7f10ad03-80a8-40e6-825e-056de006c567

	measure '% Số CH đạt thu thập KHTN' = DIVIDE([Số CH đạt thu thập KHTN], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: 0ff9e0a9-09a5-47f5-bcfb-5ce98b856d55

	measure '% Số CH đạt lượt tải app' = DIVIDE([Số CH đạt lượt tải app], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: 354531d9-53dc-4705-9e2b-c46377f5be82

	measure '% Số CH đạt trễ đơn giao hàng' = DIVIDE([Số CH đạt trễ đơn giao hàng], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: c187ad13-bbca-4352-8cc8-4af563f5bc08

	measure '% Số CH đạt năng suất định biên' = DIVIDE([Số CH đạt năng suất định biên], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: 398c640c-7c91-4bc7-b14e-05032c57f5cb

	measure '% Số CH đạt thành công đơn Online' = DIVIDE([Số CH đạt thành công đơn Online], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: 4d9e7b50-9286-4e88-be0e-8eb7eaf2c2c2

	measure '% Số CH đạt tư vấn smember' = DIVIDE([Số CH đạt tư vấn smember], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: fffbedf2-fefe-46c3-9f26-7633532f6c01

	measure '% Số CH đạt turnover rate' = DIVIDE([Số CH đạt turnover rate], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: c6ba01d9-4445-41b0-b0e4-beaa546cbe4d

	measure '% Số CH ko đạt' = DIVIDE([Số CH ko đạt], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: b651c320-fc67-4796-b4fc-9bebbc6fb381

	measure '% Số CH ko thu thập KHTN' = DIVIDE([Số CH ko thu thập KHTN], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: 6b9afc0a-3e55-42bd-b9ba-a93655f8b0fc

	measure '% Số CH ko lượt tải app' = DIVIDE([Số CH ko lượt tải app], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: 5d7e8b11-f7c3-4a43-9820-36f3b98409ef

	measure '% Số CH ko trễ đơn giao hàng' = DIVIDE([Số CH ko trễ đơn giao hàng], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: 8eace179-f298-4261-b9ff-cdf6990c7e44

	measure '% Số CH ko năng suất định biên' = DIVIDE([Số CH ko năng suất định biên], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: ad17ee2d-59f4-4279-acef-34f392fd601c

	measure '% Số CH ko thành công đơn Online' = DIVIDE([Số CH ko thành công đơn Online], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: 697caf54-0dd7-4e67-acac-3b1a2ecc7551

	measure '% Số CH ko tư vấn smember' = DIVIDE([Số CH ko tư vấn smember], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: 2843eb10-382b-4d4d-82ea-696a80701d96

	measure '% Số CH ko turnover rate' = DIVIDE([Số CH ko turnover rate], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: 95065b9d-6414-4e50-bb43-fc1bcd6ed9a6

	measure filter_show = ```
			
			--Thời gian
			// VAR zf_NamThang =
			//     OR(ISFILTERED( 'DIM_Danh mục_Ngày'[Date] ), ISFILTERED( 'DIM_Danh mục_Ngày'[Giai đoạn] ))
			// VAR zNamThang =
			//     "<a> <span style='color:#C6B497'> <b> Năm tháng: </b> </a>"
			//         // & CONCATENATEX( VALUES( Dim_Date[date] ), Dim_Date[date], ", " ) & "."
			//         & "Từ " & MIN('DIM_Danh mục_Ngày'[Date])
			//         & " đến " & MAX('DIM_Danh mục_Ngày'[Date]) & "."
			--Địa điểm
			VAR zf_Mien =
			    ISFILTERED( 'DIM_Danh mục_Miền'[Miền] )
			VAR zMien =
			    "<a> <span style='color:#C6B497'> <b> Miền: </b> </a>"
			        & CONCATENATEX( VALUES( 'DIM_Danh mục_Miền'[Miền] ), 'DIM_Danh mục_Miền'[Miền], ", " ) & "."
			
			VAR zf_TinhThanh =
			    ISFILTERED( 'DIM_Danh mục_Phòng ban'[Province] )
			VAR zTinhThanh =
			    "<a> <span style='color:#C6B497'> <b> Tỉnh thành: </b> </a>"
			        & CONCATENATEX( VALUES( 'DIM_Danh mục_Phòng ban'[Province] ), 'DIM_Danh mục_Phòng ban'[Province], ", " ) & "."
			
			VAR zf_TenShop =
			    ISFILTERED( 'DIM_Danh mục_Phòng ban'[Cửa hàng] )
			VAR zTenShop =
			    "<a> <span style='color:#C6B497'> <b> Tên shop: </b> </a>"
			        & CONCATENATEX( VALUES( 'DIM_Danh mục_Phòng ban'[Cửa hàng] ), 'DIM_Danh mục_Phòng ban'[Cửa hàng], ", " ) & "." 
			
			--Khác
			VAR zf_AM =
			    ISFILTERED( 'DIM_Danh mục_Phòng ban'[AM] )
			VAR zAM =
			    "<a> <span style='color:#C6B497'> <b> AM: </b> </a>"
			        & CONCATENATEX( VALUES( 'DIM_Danh mục_Phòng ban'[AM] ), 'DIM_Danh mục_Phòng ban'[AM], ", " ) & "."
			
			VAR zf_SM =
			    ISFILTERED( AM_SM_Current_Month[SM/SUP] )
			VAR zSM =
			    "<a> <span style='color:#C6B497'> <b> SM/SUP: </b> </a>"
			        & CONCATENATEX( VALUES( AM_SM_Current_Month[SM/SUP] ), AM_SM_Current_Month[SM/SUP], ", " ) & "."
			
			VAR zf_Size =
			    ISFILTERED( 'DIM_Danh mục_Phòng ban'[Size] )
			VAR zSize =
			    "<a> <span style='color:#C6B497'> <b> Size: </b> </a>"
			        & CONCATENATEX( VALUES( 'DIM_Danh mục_Phòng ban'[Size] ), 'DIM_Danh mục_Phòng ban'[Size], ", " ) & "."
			
			VAR zf_DanhGia =
			    ISFILTERED( 'DIM_Danh mục_Đánh giá'[Đánh giá] )
			VAR zDanhGia =
			    "<a> <span style='color:#C6B497'> <b> Kết quả đánh giá: </b> </a>"
			        & CONCATENATEX( VALUES( 'DIM_Danh mục_Đánh giá'[Đánh giá] ), 'DIM_Danh mục_Đánh giá'[Đánh giá], ", " ) & "."
			
			--Filter
			// VAR zf_ThoiGian =
			//     IF( 
			//         zf_NamThang = TRUE,
			//         1, 
			//         0 
			//     )
			VAR zf_DiaDiem =
			    IF(
			        zf_Mien = TRUE
			            || zf_TinhThanh = TRUE
			            || zf_TenShop = TRUE,
			        1,
			        0
			    )
			VAR zf_Khac =
			    IF(
			        zf_AM = TRUE
			            || zf_SM = TRUE
			            || zf_Size = TRUE
			            || zf_DanhGia = TRUE,
			        1,
			        0
			    )
			VAR zf_All =
			    IF( zf_DiaDiem + zf_Khac > 0, 1, 0 )
			VAR zFilter =
			    IF(
			        zf_All = 0,
			        BLANK(),
			        "<u> Bộ lọc áp dụng:</u>"
			            // & IF( zf_NamThang = TRUE, "<br>" & zNamThang, BLANK() )
			            & IF( zf_Mien = TRUE, "<br>" & zMien, BLANK() )
			            & IF( zf_TinhThanh = TRUE, "<br>" & zTinhThanh, BLANK() )          
			            & IF( zf_AM = TRUE, "<br>" & zAM, BLANK() )
			            & IF( zf_SM = TRUE, "<br>" & zSM, BLANK() )
			            & IF( zf_Size = TRUE, "<br>" & zSize, BLANK() )
			            & IF( zf_TenShop = TRUE, "<br>" & zTenShop, BLANK() )
			            & IF( zf_DanhGia = TRUE, "<br>" & zDanhGia, BLANK() )
			    )
			RETURN
			    "<i> <span style='color:white'>
			        <u> Cập nhật đến:</u>" & [Thời gian cập nhật] & "<br>" & zFilter
			    &  "</i>"
			```
		displayFolder: 1. Đánh giá Shop
		lineageTag: b4edeee3-7f6c-4b38-89f9-69ed09fdf914

	measure 'Group SM/SUP' = CONCATENATEX( VALUES( 'FACT_Đánh giá SM'[SM/SUP] ), 'FACT_Đánh giá SM'[SM/SUP], ", " )
		displayFolder: 3. Đánh giá SM
		lineageTag: 5001122b-5b51-4fa7-ba8d-18d04162e02f

	measure 'Số cửa hàng kq' = DISTINCTCOUNT('Kết quả đánh giá Shop'[Cửa hàng])
		formatString: 0
		displayFolder: 2. Chỉ tiêu
		lineageTag: 225bbf17-9fd4-4ed2-8775-57c490c8e517

	measure 'Số quản lý kq' = COUNTROWS(SUMMARIZE(FILTER('FACT_Đánh giá SM', 'FACT_Đánh giá SM'[MNV] <> BLANK()), 'FACT_Đánh giá SM'[SM/SUP]))
		formatString: 0
		displayFolder: 3. Đánh giá SM
		lineageTag: e896e956-f266-49ec-8629-48406a9b4961

	measure 'Số AM kq' = COUNTROWS(SUMMARIZE(FILTER('DIM_Danh mục_Shop_AM', 'DIM_Danh mục_Shop_AM'[AM] <> BLANK()), 'DIM_Danh mục_Shop_AM'[AM]))
		formatString: 0
		displayFolder: 4. Đánh giá AM
		lineageTag: 9368412a-074e-4c74-947a-476d2139d0d2

	measure 'Số Tỉnh kq' = CALCULATE(DISTINCTCOUNT('DIM_Danh mục_Phòng ban'[Province]), FILTER('DIM_Danh mục_Phòng ban', 'DIM_Danh mục_Phòng ban'[Key City] <> "None"))
		formatString: 0
		displayFolder: 2. Chỉ tiêu
		lineageTag: 2f1a6fd4-0305-4809-acb7-5b3de4797108

	measure 'Số cửa hàng đạt kq' = CALCULATE([Số cửa hàng kq], FILTER('DIM_Danh mục_Đánh giá', 'DIM_Danh mục_Đánh giá'[Đánh giá] = "Đạt"))
		formatString: 0
		displayFolder: 2. Chỉ tiêu
		lineageTag: e28af6a3-bcd7-446c-bc71-0f441a196b77

	measure 'Đánh giá Quý_SM' =
			
			VAR _score = AVERAGE('Kết quả đánh giá Shop'[Kds/Score])
			VAR _diem = AVERAGE('Kết quả đánh giá Shop'[Tổng chỉ tiêu đạt])
			RETURN
			SWITCH(
			    TRUE(),
			    _score >= 1 && _diem >= 9, "Xuất sắc tuyệt đối",
			    _score >= 0.8 && _diem >= 7, "Tốt",
			    _score >= 0.7 && _diem >= 5, "Khá",
			    _score >= 0.5 && _diem >= 3, "Kém",
			    _score < 0.5 && _diem < 3, "Cảnh cáo",
			    "Cảnh cáo"
			)
		displayFolder: 3. Đánh giá SM
		lineageTag: fbd2ecba-2373-4cc2-bdb4-04813870eed0

	measure 'Tổng chỉ tiêu đạt_SM' = SUM('Kết quả đánh giá Shop'[Tổng chỉ tiêu đạt])
		formatString: 0
		displayFolder: 3. Đánh giá SM
		lineageTag: 4aa09de7-0566-47a0-bd59-bd82f0afb20c

	measure 'Số tháng quản lý' = COUNTROWS(SUMMARIZE(FILTER('FACT_Đánh giá SM', 'FACT_Đánh giá SM'[MNV] <> BLANK()), 'FACT_Đánh giá SM'[StartDate]))
		formatString: 0
		displayFolder: 3. Đánh giá SM
		lineageTag: 901afb56-22fe-4cd1-bd7e-cd01fd72b839

	measure 'Số cửa hàng đánh giá_SM' = ```
			
			var xstd = CALCULATE(COUNTROWS('Kết quả đánh giá Shop'), FILTER('DIM_Danh mục_Đánh giá', 'DIM_Danh mục_Đánh giá'[Đánh giá cuối cùng] = "Xuất sắc tuyệt đối"))
			var tot = CALCULATE(COUNTROWS('Kết quả đánh giá Shop'), FILTER('DIM_Danh mục_Đánh giá', 'DIM_Danh mục_Đánh giá'[Đánh giá cuối cùng] = "Tốt"))
			var kha = CALCULATE(COUNTROWS('Kết quả đánh giá Shop'), FILTER('DIM_Danh mục_Đánh giá', 'DIM_Danh mục_Đánh giá'[Đánh giá cuối cùng] = "Khá"))
			var kem = CALCULATE(COUNTROWS('Kết quả đánh giá Shop'), FILTER('DIM_Danh mục_Đánh giá', 'DIM_Danh mục_Đánh giá'[Đánh giá cuối cùng] = "Kém"))
			var canhcao = CALCULATE(COUNTROWS('Kết quả đánh giá Shop'), FILTER('DIM_Danh mục_Đánh giá', 'DIM_Danh mục_Đánh giá'[Đánh giá cuối cùng] = "Cảnh cáo"))
			return IF(xstd + tot + kha + kem + canhcao = 0, BLANK(),             
			            IF( xstd > 0, "Xuất sắc tuyệt đối " & xstd & " | ", BLANK() )
			            & IF( tot > 0, "Tốt " & tot & " | ", BLANK() )        
			            & IF( kha > 0, "Khá " & kha & " | ", BLANK() )
			            & IF( kem > 0, "Kém " & kem & " | ", BLANK() )
			            & IF( canhcao > 0, "Cảnh cáo " & canhcao, BLANK() ))
			```
		displayFolder: 3. Đánh giá SM
		lineageTag: 957c0d57-a17b-43ba-9058-aaeb2c78547c

	measure 'Số cửa hàng đánh giá kq' =
			
			COUNTROWS('Kết quả đánh giá Shop')
		formatString: 0
		displayFolder: 2. Chỉ tiêu
		lineageTag: 2e0b52d0-9696-4c0b-8387-c4be3b6debc1

	measure XSTD = ```
			
			var thang = ADDCOLUMNS('FACT_Đánh giá SM', "DanhGiaT", RELATED('Kết quả đánh giá Shop'[Đánh giá cuối cùng]))
			var quy = SUMMARIZE(FILTER('FACT_Đánh giá SM', 'FACT_Đánh giá SM'[Quý] <> BLANK()), 'FACT_Đánh giá SM'[MNV],'FACT_Đánh giá SM'[Quý], "DanhGiaQ", [Đánh giá Quý_SM])
			return 
			SWITCH(TRUE(),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Tháng]), COUNTROWS(FILTER(thang, [DanhGiaT] = "Xuất sắc tuyệt đối")),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Quý]), COUNTROWS(FILTER(quy, [DanhGiaQ] = "Xuất sắc tuyệt đối")),
			BLANK())
			```
		formatString: 0
		displayFolder: 3. Đánh giá SM
		lineageTag: 65d77d17-16f0-4bc8-836a-4b6c18293b8d

	measure Test = IF ( ISINSCOPE ( 'DIM_Danh mục_Ngày'[Năm/Tháng] ), TRUE () )
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 2. Chỉ tiêu
		lineageTag: 80b6b2e6-a3ea-4102-8a15-1a2056407dd8

	measure TOT = ```
			
			var thang = ADDCOLUMNS('FACT_Đánh giá SM', "DanhGiaT", RELATED('Kết quả đánh giá Shop'[Đánh giá cuối cùng]))
			var quy = SUMMARIZE(FILTER('FACT_Đánh giá SM', 'FACT_Đánh giá SM'[Quý] <> BLANK()), 'FACT_Đánh giá SM'[MNV],'FACT_Đánh giá SM'[Quý], "DanhGiaQ", [Đánh giá Quý_SM])
			return 
			SWITCH(TRUE(),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Tháng]), COUNTROWS(FILTER(thang, [DanhGiaT] = "Tốt")),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Quý]), COUNTROWS(FILTER(quy, [DanhGiaQ] = "Tốt")),
			BLANK())
			```
		formatString: 0
		displayFolder: 3. Đánh giá SM
		lineageTag: 2807c239-a422-44b0-be5e-a48da79df6bc

	measure KHA = ```
			
			var thang = ADDCOLUMNS('FACT_Đánh giá SM', "DanhGiaT", RELATED('Kết quả đánh giá Shop'[Đánh giá cuối cùng]))
			var quy = SUMMARIZE(FILTER('FACT_Đánh giá SM', 'FACT_Đánh giá SM'[Quý] <> BLANK()), 'FACT_Đánh giá SM'[MNV],'FACT_Đánh giá SM'[Quý], "DanhGiaQ", [Đánh giá Quý_SM])
			return 
			SWITCH(TRUE(),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Tháng]), COUNTROWS(FILTER(thang, [DanhGiaT] = "Khá")),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Quý]), COUNTROWS(FILTER(quy, [DanhGiaQ] = "Khá")),
			BLANK())
			```
		formatString: 0
		displayFolder: 3. Đánh giá SM
		lineageTag: 84083b1b-4d4f-4955-a43e-3fda2ef02883

	measure KEM = ```
			
			var thang = ADDCOLUMNS('FACT_Đánh giá SM', "DanhGiaT", RELATED('Kết quả đánh giá Shop'[Đánh giá cuối cùng]))
			var quy = SUMMARIZE(FILTER('FACT_Đánh giá SM', 'FACT_Đánh giá SM'[Quý] <> BLANK()), 'FACT_Đánh giá SM'[MNV],'FACT_Đánh giá SM'[Quý], "DanhGiaQ", [Đánh giá Quý_SM])
			return 
			SWITCH(TRUE(),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Tháng]), COUNTROWS(FILTER(thang, [DanhGiaT] = "Kém")),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Quý]), COUNTROWS(FILTER(quy, [DanhGiaQ] = "Kém")),
			BLANK())
			```
		formatString: 0
		displayFolder: 3. Đánh giá SM
		lineageTag: bdb5b3f8-a298-4136-bf54-3701ac412a53

	measure CCAO = ```
			
			var thang = ADDCOLUMNS('FACT_Đánh giá SM', "DanhGiaT", RELATED('Kết quả đánh giá Shop'[Đánh giá cuối cùng]))
			var quy = SUMMARIZE(FILTER('FACT_Đánh giá SM', 'FACT_Đánh giá SM'[Quý] <> BLANK()), 'FACT_Đánh giá SM'[MNV],'FACT_Đánh giá SM'[Quý], "DanhGiaQ", [Đánh giá Quý_SM])
			return 
			SWITCH(TRUE(),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Tháng]), COUNTROWS(FILTER(thang, [DanhGiaT] = "Cảnh cáo")),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Quý]), COUNTROWS(FILTER(quy, [DanhGiaQ] = "Cảnh cáo")),
			BLANK())
			```
		formatString: 0
		displayFolder: 3. Đánh giá SM
		lineageTag: 91f3d22c-64d1-4766-9294-d83eca4b6814

	measure 'Điểm quy đổi_AM' =
			
			AVERAGEX(SUMMARIZE('FACT_Đánh giá AM', 'FACT_Đánh giá AM'[AM_NamThang], 'FACT_Đánh giá AM'[Điểm quy đổi]), [Điểm quy đổi])
		displayFolder: 4. Đánh giá AM
		lineageTag: ed5fc664-0ddc-4803-a4f7-b087ddd5c26e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Đánh giá Quý_AM' = VAR _score = AVERAGE('FACT_Đánh giá AM'[Score]) VAR _diem = ROUND(AVERAGE('FACT_Đánh giá AM'[Tổng chỉ tiêu đạt]),0) RETURN SWITCH( TRUE(), _score >= 1 && _diem >= 9, "Xuất sắc tuyệt đối", _score >= 0.8 && _diem >= 7, "Tốt", _score >= 0.7 && _diem >= 5, "Khá", _score >= 0.5 && _diem >= 3, "Kém", _score < 0.5 && _diem < 3, "Cảnh cáo", "Cảnh cáo" )
		displayFolder: 4. Đánh giá AM
		lineageTag: 81a3073e-d673-4e6f-ad75-05dd06e9d57d

	measure 'Số tháng quản lý vùng' = CALCULATE(DISTINCTCOUNT('FACT_Đánh giá AM'[Cửa hàng_NamThang]),FILTER('FACT_Đánh giá AM', 'FACT_Đánh giá AM'[AM] <> BLANK()))
		formatString: 0
		displayFolder: 4. Đánh giá AM
		lineageTag: 7d521691-9b29-4fc7-a03c-72f2a7ff6d0f

	measure 'Số tháng đánh giá_AM' = ```
			
			var xstd = CALCULATE(DISTINCTCOUNT('FACT_Đánh giá AM'[Cửa hàng_NamThang]), FILTER('FACT_Đánh giá AM', 'FACT_Đánh giá AM'[Đánh giá cuối cùng] = "Xuất sắc tuyệt đối"))
			var tot = CALCULATE(DISTINCTCOUNT('FACT_Đánh giá AM'[Cửa hàng_NamThang]), FILTER('FACT_Đánh giá AM', 'FACT_Đánh giá AM'[Đánh giá cuối cùng] = "Tốt"))
			var kha = CALCULATE(DISTINCTCOUNT('FACT_Đánh giá AM'[Cửa hàng_NamThang]), FILTER('FACT_Đánh giá AM', 'FACT_Đánh giá AM'[Đánh giá cuối cùng] = "Khá"))
			var kem = CALCULATE(DISTINCTCOUNT('FACT_Đánh giá AM'[Cửa hàng_NamThang]), FILTER('FACT_Đánh giá AM', 'FACT_Đánh giá AM'[Đánh giá cuối cùng] = "Kém"))
			return IF(xstd + tot + kha + kem = 0, BLANK(),             
			            IF( xstd > 0, "Xuất sắc tuyệt đối " & xstd & " | ", BLANK() )
			            & IF( tot > 0, "Tốt " & tot & " | ", BLANK() )        
			            & IF( kha > 0, "Khá " & kha & " | ", BLANK() )
			            & IF( kem > 0, "Kém " & kem & " | ", BLANK() ))
			```
		displayFolder: 4. Đánh giá AM
		lineageTag: 1ac77ce5-8869-4735-8e90-7c34fe762af2

	measure XSTD_AM = ```
			
			var quy = SUMMARIZE(FILTER('FACT_Đánh giá AM', 'FACT_Đánh giá AM'[Quý] <> BLANK()), 'FACT_Đánh giá AM'[AM],'FACT_Đánh giá AM'[Quý], "DanhGiaQ", [Đánh giá Quý_AM])
			return 
			SWITCH(TRUE(),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Tháng]), CALCULATE(DISTINCTCOUNT('FACT_Đánh giá AM'[AM]),FILTER('FACT_Đánh giá AM', 'FACT_Đánh giá AM'[Đánh giá cuối cùng] = "Xuất sắc tuyệt đối")),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Quý]), CALCULATE(DISTINCTCOUNT('FACT_Đánh giá AM'[AM]),FILTER(quy, [DanhGiaQ] = "Xuất sắc tuyệt đối")),
			BLANK())
			```
		formatString: 0
		displayFolder: 4. Đánh giá AM
		lineageTag: 49cb27cd-90b6-40cb-a98c-420a890d3d2a

	measure TOT_AM = ```
			
			var quy = SUMMARIZE(FILTER('FACT_Đánh giá AM', 'FACT_Đánh giá AM'[Quý] <> BLANK()), 'FACT_Đánh giá AM'[AM],'FACT_Đánh giá AM'[Quý], "DanhGiaQ", [Đánh giá Quý_AM])
			return 
			SWITCH(TRUE(),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Tháng]), CALCULATE(DISTINCTCOUNT('FACT_Đánh giá AM'[AM]),FILTER('FACT_Đánh giá AM', 'FACT_Đánh giá AM'[Đánh giá cuối cùng] = "Tốt")),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Quý]), CALCULATE(DISTINCTCOUNT('FACT_Đánh giá AM'[AM]),FILTER(quy, [DanhGiaQ] = "Tốt")),
			BLANK())
			```
		formatString: 0
		displayFolder: 4. Đánh giá AM
		lineageTag: 2927601a-64f5-4b43-a186-0bf53981e578

	measure KEM_AM = ```
			
			var quy = SUMMARIZE(FILTER('FACT_Đánh giá AM', 'FACT_Đánh giá AM'[Quý] <> BLANK()), 'FACT_Đánh giá AM'[AM],'FACT_Đánh giá AM'[Quý], "DanhGiaQ", [Đánh giá Quý_AM])
			return 
			SWITCH(TRUE(),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Tháng]), CALCULATE(DISTINCTCOUNT('FACT_Đánh giá AM'[AM]),FILTER('FACT_Đánh giá AM', 'FACT_Đánh giá AM'[Đánh giá cuối cùng] = "Kém")),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Quý]), CALCULATE(DISTINCTCOUNT('FACT_Đánh giá AM'[AM]),FILTER(quy, [DanhGiaQ] = "Kém")),
			BLANK())
			```
		formatString: 0
		displayFolder: 4. Đánh giá AM
		lineageTag: b603a045-002c-40ed-8000-2604d7998df8

	measure KHA_AM = ```
			
			var quy = SUMMARIZE(FILTER('FACT_Đánh giá AM', 'FACT_Đánh giá AM'[Quý] <> BLANK()), 'FACT_Đánh giá AM'[AM],'FACT_Đánh giá AM'[Quý], "DanhGiaQ", [Đánh giá Quý_AM])
			return 
			SWITCH(TRUE(),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Tháng]), CALCULATE(DISTINCTCOUNT('FACT_Đánh giá AM'[AM]),FILTER('FACT_Đánh giá AM', 'FACT_Đánh giá AM'[Đánh giá cuối cùng] = "Khá")),
			ISINSCOPE('DIM_Danh mục_Ngày'[Năm/Quý]), CALCULATE(DISTINCTCOUNT('FACT_Đánh giá AM'[AM]),FILTER(quy, [DanhGiaQ] = "Khá")),
			BLANK())
			```
		formatString: 0
		displayFolder: 4. Đánh giá AM
		lineageTag: 94b3bbcc-906d-4450-baa8-3caf8eefe0fe

	measure 'Điểm quy đổi_Shop' =
			
			var zDiem = ADDCOLUMNS('FACT_Đánh giá Shop', "DiemQD", RELATED('DIM_Danh mục_Đánh giá'[Điểm quy đổi]))
			return AVERAGEX(zDiem, [DiemQD])
		formatString: 0.00
		displayFolder: 1. Đánh giá Shop
		lineageTag: f6b19e01-8985-4b56-a06b-57863cb1d93c

	measure 'Đánh giá_Shop' =
			
			var zTotal = [Điểm quy đổi_Shop]
			var AM =
			SWITCH( true(),
			zTotal =  BLANK(), BLANK(),
			zTotal > 3.5, "Xuất sắc tuyệt đối",
			zTotal >= 2.5, "Tốt",
			zTotal >= 1.5, "Khá",
			zTotal < 1.5, "Kém",
			BLANK())
			var SM = CONCATENATEX( VALUES( 'FACT_Đánh giá Shop'[Đánh giá cuối cùng] ), 'FACT_Đánh giá Shop'[Đánh giá cuối cùng], ", " )
			return IF ( ISINSCOPE ( AM_SM_Current_Month[SM/SUP] ), SM, IF ( ISINSCOPE ( AM_SM_Current_Month[AM] ), AM, BLANK()))
		displayFolder: 1. Đánh giá Shop
		lineageTag: df80e941-6f42-48da-870e-e625d5eb2b03

	measure 'Điểm quy đổi_SMKN' = SUM('Kết quả đánh giá Shop'[Điểm SizeShop])
		displayFolder: 2. Chỉ tiêu
		lineageTag: 5b2a2734-3f3e-4b22-b085-877a9700dc91

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Maxdate_D =
			
			CALCULATE (
			    MAX ( 'DIM_Danh mục_Ngày'[Date] ),
			    FILTER (
			        'DIM_Danh mục_Ngày',
			        'DIM_Danh mục_Ngày'[Ngày_IsActive] = 1
			    )
			)
			// TODAY() - 1
		formatString: General Date
		displayFolder: 2. Chỉ tiêu
		lineageTag: de32c3af-3f20-4451-af77-c961884af804

	measure 'Target BGĐT' =
			
			0.95
		displayFolder: 2. Chỉ tiêu
		lineageTag: 11cf3119-874a-4273-97f5-f1959a107591

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dso iPhone cũ' =
			
			CALCULATE(
			    [Dso],
			    FILTER(
			        'FACT_Sale_Doanh số bán',
			        'FACT_Sale_Doanh số bán'[DMC3] = "IPHONE CŨ"
			    )
			)
		displayFolder: 2. Chỉ tiêu
		lineageTag: e7c978f9-878e-4679-b7ab-58178bb6c591

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Target iPhone cũ' = DIVIDE([Dso iPhone cũ], [Target BGĐT])
		displayFolder: 2. Chỉ tiêu
		lineageTag: ae4358d7-fa77-4d1b-8174-47fdf72c48e5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Số CH đạt sử dụng ESL' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target sử dụng ESL] >= 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: a765b3ad-5d65-4c7b-9dbb-a0b1b3ee1d49

	measure 'Số CH ko sử dụng ESL' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target sử dụng ESL] < 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: 6c149565-c5af-45ca-ac0e-0eae5cc26655

	measure '% Số CH đạt sử dụng ESL' = DIVIDE([Số CH đạt sử dụng ESL], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: ac8124c1-8c83-4dc3-948d-a14008d5c39a

	measure '% Số CH ko sử dụng ESL' = DIVIDE([Số CH ko sử dụng ESL], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: ba03b798-4474-48ec-b30d-8193b699483a

	measure 'Số cửa hàng_AM' = DISTINCTCOUNT('FACT_Đánh giá AM'[Cửa hàng])
		formatString: 0
		displayFolder: 4. Đánh giá AM
		lineageTag: 0fb77962-669a-4af0-a7f0-602faa96a1ee

	measure Dso+voucher =
			
			CALCULATE (
			    SUM ( 'FACT_Sale_Doanh số bán'[Dso+Voucher] ),
			    FILTER (
			        'FACT_Sale_Doanh số bán',
			        'FACT_Sale_Doanh số bán'[IsSale] = 1
			    )
			)
		displayFolder: 2. Chỉ tiêu
		lineageTag: 7fecc761-e1f1-4a84-97f5-23ac056973cd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Target Bán kèm' =
			
			CALCULATE (
			    SUM (FACT_GSheet_Target_Shop_Daily[Target]),
			    FILTER (
			        FACT_GSheet_Target_Shop_Daily,
			        FACT_GSheet_Target_Shop_Daily[Type] = "BÁN KÈM TARGET"
			    )
			)
		displayFolder: 2. Chỉ tiêu
		lineageTag: 3a90228d-5eee-4dc4-8ccc-c3b932fbd2a9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Target PK1' =
			
			CALCULATE (
			    SUM (FACT_GSheet_Target_Shop_Daily[Target]),
			    FILTER (
			        FACT_GSheet_Target_Shop_Daily,
			        FACT_GSheet_Target_Shop_Daily[Type] = "PK1 TARGET"
			    )
			)
		displayFolder: 2. Chỉ tiêu
		lineageTag: 52e300a2-ad85-4d02-9965-b4674eac69d1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Target PK2' =
			
			CALCULATE (
			    SUM (FACT_GSheet_Target_Shop_Daily[Target]),
			    FILTER (
			        FACT_GSheet_Target_Shop_Daily,
			        FACT_GSheet_Target_Shop_Daily[Type] = "PK2 TARGET"
			    )
			)
		displayFolder: 2. Chỉ tiêu
		lineageTag: aa889616-3eea-4f95-968d-d5c11629ab3d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Target Android' =
			
			CALCULATE (
			    SUM (FACT_GSheet_Target_Shop_Daily[Target]),
			    FILTER (
			        FACT_GSheet_Target_Shop_Daily,
			        FACT_GSheet_Target_Shop_Daily[Type] = "Android"
			    )
			)
		displayFolder: 2. Chỉ tiêu
		lineageTag: 32fd5766-d930-4608-94ff-531ead986588

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dso Bán kèm' =
			
			CALCULATE (
			    [Dso+voucher],
			    FILTER (
			        'DIM_Danh mục_Nhóm hàng',
			        'DIM_Danh mục_Nhóm hàng'[Bán kèm] = 1
			    )
			)
		displayFolder: 2. Chỉ tiêu
		lineageTag: 69710daa-9170-45ad-bbb3-b37e92210af8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dso PK1' =
			
			CALCULATE (
			    [Dso],
			    FILTER (
			        'DIM_Danh mục_Nhóm hàng',
			        'DIM_Danh mục_Nhóm hàng'[Nhóm hàng cấp 2] = "PHỤ KIỆN 1"
			    )
			)
		displayFolder: 2. Chỉ tiêu
		lineageTag: a885f6ed-80bb-4fb7-825e-8a66e1778878

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dso PK2' =
			
			CALCULATE (
			    [Dso],
			    FILTER (
			        'DIM_Danh mục_Nhóm hàng',
			        'DIM_Danh mục_Nhóm hàng'[Nhóm hàng cấp 2] = "PHỤ KIỆN 2"
			    )
			)
		displayFolder: 2. Chỉ tiêu
		lineageTag: 7580ec82-c4f5-4956-a8d0-947a05275b83

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Slg Android' = ```
			
			VAR Slg_nhom1 =
			    CALCULATE (
			        [Slg],
			        FILTER (
			            'DIM_Danh mục_Nhóm hàng',
			            'DIM_Danh mục_Nhóm hàng'[Nhóm] = "ANDROID"
			            && 'DIM_Danh mục_Nhóm hàng'[Thuộc tính]= "MỚI"
			            && 'DIM_Danh mục_Nhóm hàng'[Phân nhóm] = "NHÓM 1"
			            && 'DIM_Danh mục_Nhóm hàng'[Nhóm hàng] <> "NOKIA CTM"
			        ),      
			        FILTER (
			            'D_Sản phẩm',
			            'D_Sản phẩm'[Android_exp] = BLANK () 
			        )
			    )
			VAR Slg_nhom2 =
			    CALCULATE (
			        [Slg],
			        FILTER (
			            'DIM_Danh mục_Nhóm hàng',
			            'DIM_Danh mục_Nhóm hàng'[Nhóm] = "ANDROID"
			                && 'DIM_Danh mục_Nhóm hàng'[Thuộc tính]= "MỚI"
			                && 'DIM_Danh mục_Nhóm hàng'[Phân nhóm] = "NHÓM 2"
			        )
			    )
			VAR Slg_nhom3 =
			    CALCULATE (
			        [Slg],
			        FILTER (
			            'DIM_Danh mục_Nhóm hàng',
			            'DIM_Danh mục_Nhóm hàng'[Nhóm] = "ANDROID"
			            && 'DIM_Danh mục_Nhóm hàng'[Thuộc tính]= "MỚI"
			            && 'DIM_Danh mục_Nhóm hàng'[Phân nhóm] = "NHÓM 3"
			            && 'DIM_Danh mục_Nhóm hàng'[Nhóm hàng] <> "MASSTEL CTM"
			        ),      
			        FILTER (
			            'D_Sản phẩm',
			            'D_Sản phẩm'[Android_exp] = BLANK () 
			        )
			    )
			VAR Slg_android = Slg_nhom1 + Slg_nhom2 + Slg_nhom3
			RETURN
			    Slg_android
			```
		displayFolder: 2. Chỉ tiêu
		lineageTag: fcbe3c74-a8e0-4fc2-bee0-e8782997c588

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Kds =
			
			var dso = DIVIDE([Dso], [Target Dso])
			var bankem = DIVIDE([Dso Bán kèm], [Target Bán kèm])
			var pk1 = DIVIDE([Dso PK1], [Target PK1])
			var pk2 = DIVIDE([Dso PK2], [Target PK2])
			var android = DIVIDE([Slg Android], [Target Android])
			return dso * 0.4 + bankem * 0.2 + pk1 * 0.2 + pk2 * 0.1 + android * 0.1
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: 2. Chỉ tiêu
		lineageTag: e4363278-8a19-4fef-b936-3f076812b4d6

	measure 'Điểm quy đổi_Quý_AM' = ```
			
			IF(DISTINCTCOUNT('FACT_Đánh giá AM'[AM_NamThang])<3, BLANK(), 
			AVERAGEX(SUMMARIZE('FACT_Đánh giá AM', 'FACT_Đánh giá AM'[AM_NamThang], 'FACT_Đánh giá AM'[Điểm quy đổi]), [Điểm quy đổi]))
			```
		displayFolder: 2. Chỉ tiêu
		lineageTag: 8d637612-333f-4911-9e72-8333c49afc22

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Điểm quy đổi_SSTAR' =
			
			var zDiem = ADDCOLUMNS('FACT_Đánh giá Shop', "DiemQD", RELATED('DIM_Danh mục_Đánh giá_'[Điểm quy đổi]))
			return AVERAGEX(zDiem, [DiemQD])
		displayFolder: 2. Chỉ tiêu
		lineageTag: dd17b22e-d789-4c4a-bf7b-cc932a8e39a8

	measure 'Số cửa hàng ko đạt Bán_kèm' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target thất thoát hàng hóa] < 1 )
			)
		formatString: 0
		displayFolder: 2. Chỉ tiêu
		lineageTag: b2fd6aa1-4d7f-42b4-9aca-163ef3a13e18

	measure '% Số cửa hàng Đạt S_Star' = DIVIDE([Số cửa hàng đạt Bán_kèm], [Số cửa hàng], 0)
		displayFolder: 2. Chỉ tiêu
		lineageTag: 92998ea7-8db8-4a79-89c4-b6fb45dcd910

	measure 'Số cửa hàng đạt Bán_kèm' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target thất thoát hàng hóa] >= 1 )
			)
		formatString: 0
		displayFolder: 2. Chỉ tiêu
		lineageTag: 5767216d-5127-476f-91c0-22cb59461144

	measure '% Số cửa hàng ko đạt S_Star' = DIVIDE([Số cửa hàng ko đạt Bán_kèm], [Số cửa hàng], 0)
		displayFolder: 2. Chỉ tiêu
		lineageTag: bb4584cf-2fc4-46e2-87ce-532ed0fdb0ff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Số CH đạt tham gia đào tạo' = DIVIDE([Số CH đạt tham gia đào tạo], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: ef2ae1a3-e3b3-4c3e-9515-d228443eec87

	measure 'Số CH đạt tham gia đào tạo' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target tham gia đào tạo] >= 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: 8b06bb1a-f624-4e71-9345-4f7504902c6e

	measure '% Số CH ko tham gia đào tạo' = DIVIDE([Số CH ko tham gia đào tạo], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: 76f7f490-a4b5-4759-8dd7-f245b6d2dee2

	measure 'Số CH ko tham gia đào tạo' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target tham gia đào tạo] < 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: e462a43f-39a4-42c2-b38c-d0bc522ce7b6

	measure 'Nhân sự mới' = ```
			
			CALCULATE(
			    COUNTROWS('F_Ngày nhận việc'),
			    FILTER(
			        'DIM_Danh mục_Ngày',
			        'DIM_Danh mục_Ngày'[Năm] >= 2022
			    ),
			    FILTER(
			        'DIM_Danh mục_Phòng ban',
			        'DIM_Danh mục_Phòng ban'[Cửa hàng] <> BLANK()
			    )
			)
			
			```
		formatString: 0
		displayFolder: 2. Chỉ tiêu
		lineageTag: d8776101-151e-46e9-b728-8f5a8ff82c1d

	measure 'Nhân sự rời đi' = ```
			
			CALCULATE(
			    COUNTROWS('F_Ngày kết thúc'),
			    FILTER(
			        'DIM_Danh mục_Ngày',
			        'DIM_Danh mục_Ngày'[Năm] >= 2022
			    ),
			    FILTER(
			        'DIM_Danh mục_Phòng ban',
			        'DIM_Danh mục_Phòng ban'[Cửa hàng] <> BLANK()
			    )
			)
			
			```
		formatString: 0
		displayFolder: 2. Chỉ tiêu
		lineageTag: f220d879-1448-4c5f-95d4-7fe680edc1bf

	measure 'Nhân sự còn lại' = ```
			
			IF (
			    MAX ( 'DIM_Danh mục_Ngày'[Năm] ) >= 2022,
			        CALCULATE (
			            SUM ( 'F_Employee'[NhanSuConLai] ),
			            FILTER (
			                'F_Employee',
			                'F_Employee'[IsChinhThuc] = 0
			            ),
			            FILTER (
			                'DIM_Danh mục_Ngày',
			                'DIM_Danh mục_Ngày'[Năm/Tháng_Index] = MAX ( 'DIM_Danh mục_Ngày'[Năm/Tháng_Index] )
			            ),
			            FILTER(
			            'DIM_Danh mục_Phòng ban',
			            'DIM_Danh mục_Phòng ban'[Cửa hàng] <> BLANK()
			            )
			    ),
			    BLANK()
			)
			
			```
		formatString: 0
		displayFolder: 2. Chỉ tiêu
		lineageTag: 7fb2d3cd-1505-4f58-b648-bcff5a29d913

	measure 'Số ngày thực hiện' =
			
			CALCULATE (
			    DISTINCTCOUNT('DIM_Danh mục_Ngày'[Date]),
			    FILTER (
			        'DIM_Danh mục_Ngày',
			        'DIM_Danh mục_Ngày'[Ngày_IsActive] = 1
			    )
			)
		formatString: 0
		displayFolder: 2. Chỉ tiêu
		lineageTag: b700cef4-bcd0-48de-8164-20d39767a5a9

	measure 'Công thực tế' =
			
			CALCULATE(
			    SUM( 'F_Công chi tiết'[Tổng giờ] ),
			    FILTER(
			        'F_Công chi tiết',
			        'F_Công chi tiết'[Vị trí mới] <> BLANK()
			            && 'F_Công chi tiết'[Vị trí mới] <> "PG"
			            && 'F_Công chi tiết'[Vị trí mới] <> "Tiếp đón"
			            && 'F_Công chi tiết'[IsHocviec] = "Không"
			    )
			)
		displayFolder: 2. Chỉ tiêu
		lineageTag: 542528a5-b2a9-48ff-94dc-8f3913bb244a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Color Format' = ```
			
			VAR esl = SELECTEDVALUE('FACT_Đánh giá Shop'[% Target sử dụng ESL])
			VAR app = SELECTEDVALUE('FACT_Đánh giá Shop'[% Target lượt tải app])
			VAR nang_suat = SELECTEDVALUE('FACT_Đánh giá Shop'[% Target năng suất định biên])
			VAR dao_tao = SELECTEDVALUE('FACT_Đánh giá Shop'[% Target tham gia đào tạo])
			VAR khtn = SELECTEDVALUE('FACT_Đánh giá Shop'[% Target thu thập KHTN])
			VAR onl = SELECTEDVALUE('FACT_Đánh giá Shop'[% Target thành công đơn Online])
			VAR that_thoat = SELECTEDVALUE('FACT_Đánh giá Shop'[% Target thất thoát hàng hóa])
			VAR tre_don = SELECTEDVALUE('FACT_Đánh giá Shop'[% Target trễ đơn giao hàng])
			VAR turnover = SELECTEDVALUE('FACT_Đánh giá Shop'[% Target turnover rate])
			VAR smem = SELECTEDVALUE('FACT_Đánh giá Shop'[% Target tư vấn smember])
			VAR _value =
			COALESCE(esl, turnover, nang_suat, app, tre_don, onl, that_thoat, dao_tao, smem, khtn)
			RETURN
			SWITCH(
			    TRUE(),
			    _value >= 1, "#A3D9A5",
			    _value >= 0.8, "#FFDD99",
			    _value < 0.8, "#FF9999",
			    BLANK()
			)
			
			
			```
		displayFolder: 2. Chỉ tiêu
		lineageTag: dd318e6c-7229-4a4b-ada7-cca3a3173988

	measure 'Số CH ko thất thoát hàng hóa' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target thất thoát hàng hóa] < 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: e91ecda4-9178-4c5c-8002-5edd2f18d732

	measure 'Số CH đạt thất thoát hàng hóa' =
			
			CALCULATE(
			    [Số cửa hàng],
			    FILTER( 'FACT_Đánh giá Shop', 'FACT_Đánh giá Shop'[% Target thất thoát hàng hóa] >= 1 )
			)
		formatString: 0
		displayFolder: 1. Đánh giá Shop
		lineageTag: e16938f1-afe8-477b-b769-b9bc424f4451

	measure '% Số CH đạt thất thoát hàng hóa' = DIVIDE([Số CH đạt thất thoát hàng hóa], [Số cửa hàng], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Đánh giá Shop
		lineageTag: 4842baa7-f831-4368-927d-61cacb860fb1

	measure '% Số CH ko thất thoát hàng hóa' = DIVIDE([Số CH ko thất thoát hàng hóa], [Số cửa hàng], 0)
		displayFolder: 1. Đánh giá Shop
		lineageTag: 02a76af5-bf57-45d7-9205-91752253b777

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Score_SM = SUM('Kết quả đánh giá Shop'[Kds/Score])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 3. Đánh giá SM
		lineageTag: 5092b737-b0e0-43f5-b790-6d7b82df29f6

	measure 'Test Max Date' = MAX ( CurrentDate[Date] )
		formatString: General Date
		lineageTag: ad192e18-8bca-45b8-9b03-259ef67c3395

	column Column
		isHidden
		formatString: 0
		displayFolder: 2. Chỉ tiêu
		lineageTag: 2b0a7415-7fc0-48f1-b1e1-7aba49e85a02
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition Measure = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 861f3f6dfdd94bdba3dc2e40b8697f1e

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

